# Generated by Django 5.2.16 on 2026-08-13 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0012_farmacia_segmento_red_farmacia_tiene_backup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadMensualEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('primer_heartbeat_en', models.DateTimeField(auto_now_add=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividad_mensual', to='catalogo.estacion')),
            ],
            options={
                'verbose_name': 'Actividad mensual de estación',
                'verbose_name_plural': 'Actividad mensual de estaciones',
                'db_table': 'actividad_mensual_estacion',
                'ordering': ['-anio', '-mes', 'estacion__codigo'],
                'unique_together': {('estacion', 'anio', 'mes')},
            },
        ),
    ]
