# Generated by Django 5.2.16 on 2026-07-17 20:29

import apps.despliegues.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despliegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Versión del POS que contiene este paquete, ej. 4.2.1', max_length=30)),
                ('archivo', models.FileField(upload_to=apps.despliegues.models.ruta_archivo_despliegue)),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('descripcion', models.TextField(blank=True)),
                ('modo_aplicacion', models.CharField(choices=[('inmediato', 'Aplicar inmediatamente al descargar'), ('ventana', 'Descargar ya, aplicar en ventana programada'), ('cierre_pos', 'Aplicar cuando el POS se cierre')], max_length=20)),
                ('ventana_fecha_hora', models.DateTimeField(blank=True, help_text='Requerido si el modo de aplicación es "ventana programada".', null=True)),
                ('destino_tipo', models.CharField(choices=[('cadena', 'Toda la cadena'), ('grupos', 'Grupos específicos'), ('farmacias', 'Farmacias específicas'), ('estaciones', 'Estaciones específicas')], max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('publicando', 'Publicando'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=25)),
                ('umbral_error_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='% de estaciones en error a partir del cual el despliegue se pausa automáticamente.', max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despliegues_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despliegues_creados', to=settings.AUTH_USER_MODEL)),
                ('estaciones', models.ManyToManyField(blank=True, related_name='despliegues', to='catalogo.estacion')),
                ('farmacias', models.ManyToManyField(blank=True, related_name='despliegues', to='catalogo.farmacia')),
                ('grupos', models.ManyToManyField(blank=True, related_name='despliegues', to='catalogo.grupo')),
            ],
            options={
                'db_table': 'despliegue',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoDespliegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('publicado', 'Publicado'), ('descargando', 'Descargando'), ('descargado', 'Descargado'), ('verificado', 'Hash verificado'), ('aplicando', 'Aplicando'), ('aplicado', 'Aplicado'), ('error', 'Error'), ('rollback', 'Rollback ejecutado')], default='pendiente', max_length=20)),
                ('version_previa', models.CharField(blank=True, max_length=30)),
                ('version_nueva', models.CharField(blank=True, max_length=30)),
                ('detalle_error', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('despliegue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='despliegues.despliegue')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_despliegue', to='catalogo.estacion')),
            ],
            options={
                'db_table': 'resultado_despliegue',
                'ordering': ['despliegue', 'estacion'],
                'unique_together': {('despliegue', 'estacion')},
            },
        ),
        migrations.CreateModel(
            name='EventoDespliegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.CharField(choices=[('publicado', 'Publicado por el panel'), ('recibido', 'Recibido por el agente'), ('descargado', 'Descargado'), ('hash_verificado', 'Hash verificado'), ('pos_cerrado', 'POS cerrado'), ('aplicado', 'Archivos aplicados'), ('pos_relanzado', 'POS relanzado'), ('ok', 'Confirmado OK'), ('error', 'Error'), ('rollback', 'Rollback ejecutado')], max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='despliegues.resultadodespliegue')),
            ],
            options={
                'db_table': 'evento_despliegue',
                'ordering': ['resultado', 'timestamp'],
            },
        ),
    ]
