# Generated by Django 5.2.16 on 2026-07-20 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despliegues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despliegue',
            name='despliegue_origen',
            field=models.ForeignKey(blank=True, help_text='Si este despliegue es la promoción de un anillo anterior a uno más amplio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promovidos', to='despliegues.despliegue'),
        ),
    ]
