# Generated by Django 5.2.16 on 2026-07-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despliegues', '0002_despliegue_despliegue_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='despliegue',
            name='freno_omitido',
            field=models.BooleanField(default=False, help_text='Si el operador reanudó a pesar del freno automático: no se vuelve a frenar por error.'),
        ),
    ]
