# Generated by Django 5.2.16 on 2026-08-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despliegues', '0004_despliegue_unidad_negocio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventodespliegue',
            options={'ordering': ['resultado', 'timestamp', 'pk']},
        ),
    ]
