# Generated by Django 5.2.16 on 2026-08-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despliegues', '0005_alter_eventodespliegue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despliegue',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('aprobar_despliegue', 'Puede aprobar un despliegue pendiente de aprobación')]},
        ),
    ]
