"""Borrar una estación deja de llevarse el acta de sus despliegues.

`ResultadoDespliegue.estacion` pasa de CASCADE a PROTECT. Esa fila, con sus
`EventoDespliegue`, es lo único que responde "¿esta estación recibió la 2.5.0?", y
alimenta el informe de despliegues. Con CASCADE, borrar una estación desde el admin la
borraba en silencio: sin aviso y sin rastro de que existió.

El proyecto ya aplica el criterio contrario donde importa — `EventoAuditoria.usuario` es
SET_NULL, así que borrar a una persona no borra lo que hizo. El historial de despliegues
era más frágil que la auditoría, y no hay razón para que lo sea.

No cambia nada de lo que ya está guardado: solo cambia qué pasa al intentar borrar una
estación con historial. A partir de ahora falla y obliga a decidir, que es la pausa que se
quiere en ese momento.

`ResultadoDespliegue.despliegue` sigue en CASCADE a propósito: ahí el agregado es el
despliegue y sus resultados no significan nada sin él. Las series de tiempo
(MuestraMetrica, MuestraRedFarmacia) también siguen en CASCADE: tienen retención de 30
días y no significan nada sin su estación.
"""
# Generated by Django 5.2.16 on 2026-10-07 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0035_corp_admin_y_tipo_tienda'),
        ('despliegues', '0006_alter_despliegue_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadodespliegue',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_despliegue', to='catalogo.estacion'),
        ),
    ]
