# Generated by Django 5.2.16 on 2026-07-17 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('sucursal', models.CharField(blank=True, max_length=100)),
                ('zona', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='Colaborador vigente en la empresa.')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'colaborador',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoConsumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej. MOUSE, TECLADO, TONER-HP26A', max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_consumible',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('custodio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodegas_custodiadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bodegas',
                'db_table': 'bodega',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('LAP', 'Laptop'), ('DSK', 'Desktop'), ('IMP', 'Impresora'), ('SRV', 'Servidor'), ('NET', 'Red (switch/router)'), ('TAB', 'Tablet'), ('UPS', 'UPS'), ('TEL', 'Teléfono IP'), ('CAM', 'Cámara/CCTV')], max_length=3)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('vencimiento_garantia', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_bodega', 'En bodega'), ('asignado', 'Asignado'), ('en_reparacion', 'En reparación'), ('en_transito', 'En tránsito'), ('dado_de_baja', 'Dado de baja')], default='en_bodega', max_length=15)),
                ('estado_fisico_actual', models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bodega_actual', models.ForeignKey(blank=True, help_text='Bodega donde está o desde donde salió (última ubicación conocida).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.bodega')),
                ('colaborador_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_asignados', to='activos.colaborador')),
            ],
            options={
                'db_table': 'activo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EventoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('ingreso', 'Ingreso a bodega'), ('asignacion', 'Asignación a colaborador'), ('consumible_entregado', 'Consumible entregado'), ('devolucion', 'Devolución de colaborador'), ('envio_reparacion', 'Enviado a reparación'), ('retorno_reparacion', 'Retorno de reparación'), ('baja', 'Dado de baja'), ('transito', 'En tránsito entre bodegas')], max_length=25)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='activos.activo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evento_activo',
                'ordering': ['activo', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oc', models.CharField(max_length=30, unique=True, verbose_name='N° Orden de Compra')),
                ('proveedor', models.CharField(max_length=150)),
                ('fecha_emision', models.DateField()),
                ('novedad_recepcion', models.TextField(blank=True, help_text='Faltantes, daños o diferencias frente a la OC.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de recepción'), ('recibida', 'Recibida')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bodegas_destino', models.ManyToManyField(blank=True, related_name='ordenes_compra', to='activos.bodega')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'db_table': 'orden_compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.ordencompra'),
        ),
        migrations.CreateModel(
            name='StockBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='activos.bodega')),
                ('tipo_consumible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='activos.tipoconsumible')),
            ],
            options={
                'db_table': 'stock_bodega',
                'ordering': ['bodega', 'tipo_consumible'],
                'unique_together': {('bodega', 'tipo_consumible')},
            },
        ),
    ]
