# Generated by Django 5.2.16 on 2026-07-27 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_categoriaequipo_departamento_empresa_marca_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='almacenamiento_gb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Almacenamiento (GB)'),
        ),
        migrations.AddField(
            model_name='activo',
            name='baja_recomendada',
            field=models.BooleanField(default=False, help_text='Un mantenimiento marcó este activo para posible baja; un humano debe decidir con registrar_baja.'),
        ),
        migrations.AddField(
            model_name='activo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.categoriaequipo'),
        ),
        migrations.AddField(
            model_name='activo',
            name='codigo_sap',
            field=models.CharField(blank=True, max_length=30, verbose_name='Código SAP'),
        ),
        migrations.AddField(
            model_name='activo',
            name='condicion_al_recibir',
            field=models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('reacondicionado', 'Reacondicionado')], max_length=20),
        ),
        migrations.AddField(
            model_name='activo',
            name='marca_nueva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.marca'),
        ),
        migrations.AddField(
            model_name='activo',
            name='procesador',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activo',
            name='ram_gb',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='RAM (GB)'),
        ),
    ]
