# Generated by Django 5.2.16 on 2026-07-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_marca_texto_a_fk_definitivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoactivo',
            name='tipo_evento',
            field=models.CharField(choices=[('ingreso', 'Ingreso a bodega'), ('asignacion', 'Asignación a colaborador'), ('consumible_entregado', 'Consumible entregado'), ('devolucion', 'Devolución de colaborador'), ('envio_reparacion', 'Enviado a reparación'), ('retorno_reparacion', 'Retorno de reparación'), ('baja', 'Dado de baja'), ('baja_recomendada', 'Baja recomendada (mantenimiento)'), ('transito', 'En tránsito entre bodegas')], max_length=25),
        ),
    ]
