# Generated by Django 5.2.16 on 2026-07-27 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_alter_eventoactivo_tipo_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Control de concurrencia optimista (equivalente a @Version en InvTICS).'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('recepcion_parcial', 'Recepción parcial'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='emitida', max_length=20),
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('activo', 'Activo'), ('consumible', 'Consumible')], max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Recepción parcial'), ('completo', 'Completo'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('version', models.PositiveIntegerField(default=0, help_text='Control de concurrencia optimista para recepciones simultáneas de la misma línea.')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_orden_compra', to='activos.categoriaequipo')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_orden_compra', to='activos.marca')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='activos.ordencompra')),
                ('tipo_consumible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_orden_compra', to='activos.tipoconsumible')),
            ],
            options={
                'verbose_name': 'Línea de orden de compra',
                'verbose_name_plural': 'Líneas de orden de compra',
                'db_table': 'orden_compra_detalle',
                'ordering': ['orden_compra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_lote', models.CharField(blank=True, max_length=50)),
                ('tipo_item', models.CharField(choices=[('activo', 'Activo'), ('consumible', 'Consumible')], max_length=10)),
                ('cantidad_recibida', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('aplicado', 'Aplicado'), ('anulado', 'Anulado')], default='aplicado', max_length=15)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='activos.bodega')),
                ('custodio_receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='activos.colaborador')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='activos.ordencompra')),
                ('orden_compra_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='activos.ordencompradetalle')),
                ('recepcionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepción de lote',
                'verbose_name_plural': 'Recepciones de lote',
                'db_table': 'recepcion_lote',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ingreso_consumible', 'Ingreso de consumible (compra)'), ('traslado', 'Traslado entre bodegas'), ('ajuste', 'Ajuste de inventario')], max_length=20)),
                ('cantidad', models.IntegerField(help_text='Positivo en ingresos/traslados de entrada; negativo en ajustes a la baja.')),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha_efectiva', models.DateTimeField(auto_now_add=True)),
                ('bodega_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='activos.bodega')),
                ('bodega_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='activos.bodega')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='activos.ordencompra')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('tipo_consumible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='activos.tipoconsumible')),
                ('recepcion_lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='activos.recepcionlote')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'db_table': 'movimiento_inventario',
                'ordering': ['-fecha_efectiva'],
            },
        ),
    ]
