# Generated by Django 5.2.16 on 2026-07-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_migrar_estado_pendiente_a_emitida'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cargo_directorio',
            field=models.CharField(blank=True, help_text='Cargo tal como lo reporta RRHH.', max_length=100),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo_nueva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='activos.cargo'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='departamento_directorio',
            field=models.CharField(blank=True, help_text='Departamento tal como lo reporta RRHH.', max_length=100),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='origen_sync',
            field=models.BooleanField(default=False, help_text='True si este registro vino de una sincronización con RRHH (aún sin implementar).'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sincronizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='Agencia/local donde trabaja, usada para agrupar la visita técnica de mantenimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='activos.ubicacion'),
        ),
    ]
