# Generated by Django 5.2.16 on 2026-07-27 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_cargo_texto_a_fk_definitivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('url', 'URL (API externa)'), ('archivo', 'Archivo (CSV/Excel)')], max_length=10)),
                ('creados', models.PositiveIntegerField(default=0)),
                ('actualizados', models.PositiveIntegerField(default=0)),
                ('inactivados', models.PositiveIntegerField(default=0)),
                ('reactivados', models.PositiveIntegerField(default=0)),
                ('sin_cambios', models.PositiveIntegerField(default=0)),
                ('advertencias', models.PositiveIntegerField(default=0)),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True)),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syncs_ejecutados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejecución de sync RRHH',
                'verbose_name_plural': 'Ejecuciones de sync RRHH',
                'db_table': 'sync_ejecucion',
                'ordering': ['-ejecutado_en'],
            },
        ),
        migrations.CreateModel(
            name='SyncCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creado', 'Creado'), ('actualizado', 'Actualizado'), ('inactivado', 'Inactivado'), ('reactivado', 'Reactivado'), ('advertencia', 'Advertencia'), ('alerta_activos', 'Alerta: tiene activos asignados')], max_length=20)),
                ('cedula', models.CharField(max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_sync', to='activos.colaborador')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='activos.syncejecucion')),
            ],
            options={
                'db_table': 'sync_cambio',
                'ordering': ['ejecucion', 'cedula'],
            },
        ),
    ]
