# Generated by Django 5.2.16 on 2026-07-29 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0012_syncejecucion_synccambio'),
        ('catalogo', '0008_unidadnegocio_farmacia_fecha_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='unidad_negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='catalogo.unidadnegocio'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='unidad_negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='catalogo.unidadnegocio'),
        ),
    ]
