# Generated by Django 5.2.16 on 2026-08-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0013_activo_unidad_negocio_colaborador_unidad_negocio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventoactivo',
            options={'ordering': ['activo', 'timestamp', 'pk']},
        ),
    ]
