# Generated by Django 5.2.16 on 2026-08-05 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0014_alter_eventoactivo_options'),
        ('mantenimiento', '0007_remove_mantenimiento_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
