# Generated by Django 5.2.16 on 2026-08-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0015_delete_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ingreso_consumible', 'Ingreso de consumible (compra)'), ('traslado', 'Traslado entre bodegas'), ('ajuste', 'Ajuste de inventario'), ('salida_consumo', 'Salida por consumo (repuesto usado en mantenimiento)')], max_length=20),
        ),
    ]
