# Generated by Django 5.2.16 on 2026-08-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0016_alter_movimientoinventario_tipo_movimiento'),
        ('catalogo', '0018_farmacia_ip_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='estacion',
            field=models.OneToOneField(blank=True, help_text='Estación RMM vinculada automáticamente por número de serie coincidente (ver apps.activos.services.vincular_activos_por_numero_serie).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activo_vinculado', to='catalogo.estacion'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='unidad_negocio',
            field=models.ForeignKey(blank=True, help_text='Vacío = bodega compartida (ej. central), visible para todas las unidades de negocio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bodegas', to='catalogo.unidadnegocio'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='unidad_negocio',
            field=models.ForeignKey(blank=True, help_text='Vacío = orden de compra compartida, visible para todas las unidades de negocio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='catalogo.unidadnegocio'),
        ),
        migrations.AddField(
            model_name='tipoconsumible',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, help_text='Alertar cuando el stock de una bodega caiga por debajo. 0 = no vigilar.'),
        ),
    ]
