# Generated by Django 5.2.16 on 2026-08-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0017_activo_estacion_bodega_unidad_negocio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('en_bodega', 'En bodega'), ('asignado', 'Asignado'), ('en_reparacion', 'En reparación'), ('dado_de_baja', 'Dado de baja')], default='en_bodega', max_length=15),
        ),
    ]
