# Generated by Django 5.2.16 on 2026-08-23 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0018_alter_activo_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Login al panel de este colaborador, si tiene uno (ej. técnicos de soporte con acceso propio) — no todo Colaborador necesita una cuenta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to=settings.AUTH_USER_MODEL),
        ),
    ]
