# Generated by Django 5.2.16 on 2026-08-23 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0019_colaborador_usuario'),
        ('catalogo', '0020_farmacia_administrador_farmacia_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='farmacia',
            field=models.ForeignKey(blank=True, help_text='Farmacia donde está físicamente el equipo -- vacío = administrativo/oficina o en bodega. Se completa solo si el equipo tiene una Estación RMM vinculada; para el resto (impresoras, monitores, PCs sin agente) se asigna a mano.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='catalogo.farmacia'),
        ),
        migrations.AlterField(
            model_name='eventoactivo',
            name='tipo_evento',
            field=models.CharField(choices=[('ingreso', 'Ingreso a bodega'), ('asignacion', 'Asignación a colaborador'), ('consumible_entregado', 'Consumible entregado'), ('devolucion', 'Devolución de colaborador'), ('envio_reparacion', 'Enviado a reparación'), ('retorno_reparacion', 'Retorno de reparación'), ('baja', 'Dado de baja'), ('baja_recomendada', 'Baja recomendada (mantenimiento)'), ('transito', 'En tránsito entre bodegas'), ('ubicacion_actualizada', 'Ubicación (farmacia) actualizada')], max_length=25),
        ),
    ]
