# Generated by Django 5.2.16 on 2026-09-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0020_activo_farmacia_alter_eventoactivo_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='codigo_sap',
            field=models.CharField(blank=True, max_length=30, verbose_name='Código Activo'),
        ),
    ]
