# Generated by Django 5.2.16 on 2026-09-12 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0021_alter_activo_codigo_sap'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='Solo para equipos SIN estación RMM vinculada. Si el activo tiene estación, la IP la reporta el agente y se muestra desde ahí.', null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='mac',
            field=models.CharField(blank=True, help_text='Dirección física del equipo. Útil para reservas DHCP y para reconocerlo en el switch cuando la IP cambia.', max_length=17, validators=[django.core.validators.RegexValidator('^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$', 'Formato de MAC inválido. Se espera AA:BB:CC:DD:EE:FF.')]),
        ),
        migrations.AddField(
            model_name='activo',
            name='ubicacion_interna',
            field=models.CharField(blank=True, choices=[('rack', 'Rack'), ('caja', 'Caja / PDV'), ('bodega', 'Bodega'), ('oficina', 'Oficina'), ('otro', 'Otro')], help_text='Dónde está montado DENTRO de la farmacia. No confundir con `Ubicacion`, que es la agencia/sede y la usa el módulo de visitas técnicas.', max_length=20),
        ),
    ]
