# Generated by Django 5.2.16 on 2026-09-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0022_activo_ip_activo_mac_activo_ubicacion_interna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='tipo',
            field=models.CharField(choices=[('LAP', 'Laptop'), ('DSK', 'Desktop'), ('IMP', 'Impresora'), ('SRV', 'Servidor'), ('NET', 'Red (switch/router)'), ('TAB', 'Tablet'), ('UPS', 'UPS'), ('TEL', 'Teléfono IP'), ('CAM', 'Cámara/CCTV'), ('PIN', 'Pinpad / datáfono')], max_length=3),
        ),
    ]
