# Generated by Django 5.2.16 on 2026-09-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0023_alter_activo_tipo'),
        ('catalogo', '0026_farmacia_circuito_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='slot',
            field=models.CharField(blank=True, help_text='Qué puesto ocupa este equipo dentro del esquema estándar de la farmacia: "mikrotik", "switch", "voip", o uno atado a una estación como "impresora_A" o "medianet_B". Vacío = todavía no se sabe cuál de los puestos es.', max_length=40),
        ),
        migrations.AlterField(
            model_name='activo',
            name='tipo',
            field=models.CharField(choices=[('LAP', 'Laptop'), ('DSK', 'Desktop'), ('IMP', 'Impresora'), ('SRV', 'Servidor'), ('NET', 'Red (switch/router)'), ('TAB', 'Tablet'), ('UPS', 'UPS'), ('TEL', 'Teléfono IP'), ('CAM', 'Cámara/CCTV'), ('PIN', 'Pinpad / datáfono'), ('BIO', 'Biométrico'), ('ALM', 'Alarma SIPAO')], max_length=3),
        ),
        migrations.AlterField(
            model_name='eventoactivo',
            name='tipo_evento',
            field=models.CharField(choices=[('ingreso', 'Ingreso a bodega'), ('asignacion', 'Asignación a colaborador'), ('consumible_entregado', 'Consumible entregado'), ('devolucion', 'Devolución de colaborador'), ('envio_reparacion', 'Enviado a reparación'), ('retorno_reparacion', 'Retorno de reparación'), ('baja', 'Dado de baja'), ('baja_recomendada', 'Baja recomendada (mantenimiento)'), ('transito', 'En tránsito entre bodegas'), ('ubicacion_actualizada', 'Ubicación (farmacia) actualizada'), ('datos_red_cargados', 'Datos de red cargados (IP/MAC/serie)')], max_length=25),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('slot', ''), _negated=True), models.Q(('estado', 'dado_de_baja'), _negated=True)), fields=('farmacia', 'slot'), name='un_slot_por_farmacia'),
        ),
    ]
