# Generated by Django 5.2.16 on 2026-09-19 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0024_activo_slot_alter_activo_tipo_and_more'),
        ('catalogo', '0030_hmac_propio_confirmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='unidad_negocio',
            field=models.ForeignKey(blank=True, help_text='Vacío = personal administrativo de CRESIO, visible para todas las unidades. No hay administrativos propios de MIA o SG: el nulo es el valor correcto para ellos, no un dato pendiente de llenar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='catalogo.unidadnegocio'),
        ),
    ]
