# Generated by Django 5.2.16 on 2026-10-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0026_quitar_auditoria_de_sync_rrhh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoactivo',
            name='tipo_evento',
            field=models.CharField(choices=[('ingreso', 'Ingreso a bodega'), ('asignacion', 'Asignación a colaborador'), ('consumible_entregado', 'Consumible entregado'), ('devolucion', 'Devolución de colaborador'), ('envio_reparacion', 'Enviado a reparación'), ('retorno_reparacion', 'Retorno de reparación'), ('baja', 'Dado de baja'), ('baja_recomendada', 'Baja recomendada (mantenimiento)'), ('transito', 'En tránsito entre bodegas'), ('ubicacion_actualizada', 'Ubicación (farmacia) actualizada'), ('datos_red_cargados', 'Datos de red cargados (IP/MAC/serie)'), ('correccion_datos', 'Corrección de datos')], max_length=25),
        ),
    ]
