# Generated by Django 5.2.16 on 2026-10-08 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0027_alter_eventoactivo_tipo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Lo que no entra en ningún otro campo: de dónde salió el equipo, qué es cuando la marca no se reconoce, por qué está donde está.'),
        ),
        migrations.AddField(
            model_name='activo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='Sede o área donde está el equipo cuando NO está en una farmacia ni en bodega (matriz, oficinas). El departamento y el encargado salen de la ubicación.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.ubicacion'),
        ),
    ]
