# Generated by Django 5.2.16 on 2026-07-29 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0013_activo_unidad_negocio_colaborador_unidad_negocio'),
        ('catalogo', '0008_unidadnegocio_farmacia_fecha_apertura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCumplimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_objetivo', models.CharField(choices=[('estaciones', 'Estaciones'), ('farmacias', 'Farmacias'), ('colaboradores', 'Colaboradores')], max_length=20)),
                ('fecha_limite', models.DateField()),
                ('farmacias_aperturadas_desde', models.DateField(blank=True, help_text='Solo para objetivo Farmacias: incluye únicamente las abiertas desde esta fecha.', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cargos', models.ManyToManyField(blank=True, help_text='Solo para objetivo Colaboradores: cargos incluidos en el alcance.', related_name='actividades_cumplimiento', to='activos.cargo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unidades_negocio', models.ManyToManyField(related_name='actividades_cumplimiento', to='catalogo.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Actividad de cumplimiento',
                'verbose_name_plural': 'Actividades de cumplimiento',
                'db_table': 'actividad_cumplimiento',
                'ordering': ['fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoCumplimientoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=15)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_colaborador', to='cumplimiento.actividadcumplimiento')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_cumplimiento', to='activos.colaborador')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resultado_cumplimiento_colaborador',
                'ordering': ['colaborador__nombre'],
                'unique_together': {('actividad', 'colaborador')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoCumplimientoEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=15)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_estacion', to='cumplimiento.actividadcumplimiento')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_cumplimiento', to='catalogo.estacion')),
            ],
            options={
                'db_table': 'resultado_cumplimiento_estacion',
                'ordering': ['estacion__codigo'],
                'unique_together': {('actividad', 'estacion')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoCumplimientoFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=15)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_farmacia', to='cumplimiento.actividadcumplimiento')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_cumplimiento', to='catalogo.farmacia')),
            ],
            options={
                'db_table': 'resultado_cumplimiento_farmacia',
                'ordering': ['farmacia__codigo'],
                'unique_together': {('actividad', 'farmacia')},
            },
        ),
    ]
