# Generated by Django 5.2.16 on 2026-08-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeMqttFallido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=200)),
                ('payload_crudo', models.TextField(blank=True)),
                ('error', models.TextField()),
                ('revisado', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje MQTT fallido',
                'verbose_name_plural': 'Mensajes MQTT fallidos',
                'db_table': 'mensaje_mqtt_fallido',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('ultimo_latido', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Latido de worker',
                'verbose_name_plural': 'Latidos de worker',
                'db_table': 'worker_heartbeat',
            },
        ),
    ]
