# Generated by Django 5.2.16 on 2026-09-27 14:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_worker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolamientoRechazado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_recibido', models.CharField(help_text='El código con el que el agente intentó enrolarse.', max_length=100)),
                ('hostname', models.CharField(blank=True, help_text='Nombre de Windows del equipo: con esto se lo ubica, aunque el código esté mal.', max_length=120)),
                ('motivo', models.CharField(default='Sitio no encontrado para el código.', max_length=200)),
                ('revisado', models.BooleanField(default=False)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('intentos', models.PositiveIntegerField(default=1, help_text='El agente reintenta solo: se cuenta en vez de crear una fila por intento.')),
                ('primer_intento', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_intento', models.DateTimeField(default=django.utils.timezone.now)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolamientos_rechazados_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrolamiento rechazado',
                'verbose_name_plural': 'Enrolamientos rechazados',
                'db_table': 'enrolamiento_rechazado',
                'ordering': ['-ultimo_intento'],
                'constraints': [models.UniqueConstraint(fields=('codigo_recibido', 'hostname'), name='enrolamiento_rechazado_unico')],
            },
        ),
    ]
