# Generated by Django 5.2.16 on 2026-09-19 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0025_convencion_unidad_corporativa'),
        ('catalogo', '0030_hmac_propio_confirmado'),
        ('cuentas', '0002_perfilusuario_rbac_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, help_text='chat_id de Telegram de esta persona. Con esto, sus comandos de acción por Telegram se ejecutan con SUS permisos y quedan a su nombre en el historial. Vacío = solo puede consultar (si su chat está en TELEGRAM_CHAT_IDS_AUTORIZADOS).', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='perfilusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_chat_id', ''), _negated=True), fields=('telegram_chat_id',), name='un_chat_de_telegram_por_persona'),
        ),
    ]
