# Generated by Django 5.2.16 on 2026-10-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, help_text='chat_id de Telegram de esta persona. Con esto, sus comandos de acción por Telegram se ejecutan con SUS permisos y quedan a su nombre en el historial. Vacío = solo puede consultar (si su chat está en TELEGRAM_CHAT_IDS_AUTORIZADOS). Cargarlo aca ya habilita a la persona a consultar: desde el 7-oct-2026 no hace falta tocar el .env.', max_length=32),
        ),
    ]
