# Generated by Django 5.2.16 on 2026-08-05 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0011_alter_estacion_options_estacion_bitlocker_habilitado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacionExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conector', models.CharField(help_text='Nombre registrado en el registro de conectores', max_length=50)),
                ('direccion', models.CharField(choices=[('saliente', 'Saliente (SAIDSOFT → sistema externo)'), ('entrante', 'Entrante (sistema externo → SAIDSOFT)')], default='saliente', max_length=10)),
                ('modelo', models.CharField(help_text='Etiqueta del modelo sincronizado (ej. mantenimiento.Mantenimiento)', max_length=100)),
                ('objeto_id', models.CharField(max_length=50)),
                ('objeto_repr', models.CharField(blank=True, help_text='str() del objeto al momento del último intento', max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=10)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Últimos datos enviados al conector')),
                ('respuesta', models.JSONField(blank=True, default=dict, help_text='Última respuesta cruda del sistema externo')),
                ('ultimo_error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('unidad_negocio', models.ForeignKey(blank=True, help_text='Tenant del objeto sincronizado, derivado automáticamente. Vacío = recurso compartido o sin tenant único (mismo criterio que EventoAuditoria).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizaciones_externas', to='catalogo.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Sincronización externa',
                'verbose_name_plural': 'Sincronizaciones externas',
                'db_table': 'sincronizacion_externa',
                'ordering': ['-actualizado_en'],
                'unique_together': {('conector', 'modelo', 'objeto_id')},
            },
        ),
        migrations.CreateModel(
            name='EventoSyncExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], max_length=10)),
                ('detalle', models.TextField(blank=True)),
                ('respuesta', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sincronizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='integraciones.sincronizacionexterna')),
            ],
            options={
                'verbose_name': 'Evento de sincronización externa',
                'verbose_name_plural': 'Eventos de sincronización externa',
                'db_table': 'evento_sync_externo',
                'ordering': ['sincronizacion', 'timestamp'],
            },
        ),
    ]
