# Generated by Django 5.2.16 on 2026-08-05 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventosyncexterno',
            options={'ordering': ['sincronizacion', 'timestamp', 'pk'], 'verbose_name': 'Evento de sincronización externa', 'verbose_name_plural': 'Eventos de sincronización externa'},
        ),
    ]
