# Generated by Django 5.2.16 on 2026-07-20 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0003_estacion_monitorear_recursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuestraMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_total', models.PositiveIntegerField(blank=True, null=True)),
                ('ram_usada', models.PositiveIntegerField(blank=True, null=True)),
                ('ram_libre', models.PositiveIntegerField(blank=True, null=True)),
                ('cache', models.PositiveIntegerField(blank=True, null=True)),
                ('swap_total', models.PositiveIntegerField(blank=True, null=True)),
                ('swap_usada', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_carga_pct', models.FloatField(blank=True, help_text='% de uso de CPU (0-100).', null=True)),
                ('temperatura_c', models.FloatField(blank=True, help_text='°C del CPU, si el equipo lo expone.', null=True)),
                ('latencia_ms', models.FloatField(blank=True, help_text='Latencia de red hacia el servidor central.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='catalogo.estacion')),
            ],
            options={
                'db_table': 'muestra_metrica',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['estacion', '-timestamp'], name='muestra_met_estacio_8791ee_idx')],
            },
        ),
    ]
