# Generated by Django 5.2.16 on 2026-07-30 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_farmacia_unidad_negocio'),
        ('monitoreo', '0002_hypertable_timescaledb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('metrica', models.CharField(choices=[('cpu_carga_pct', 'CPU (%)'), ('ram_usada_pct', 'RAM (%)'), ('latencia_ms', 'Latencia (ms)'), ('temperatura_c', 'Temperatura (°C)'), ('sin_heartbeat', 'Sin heartbeat (minutos)')], max_length=20)),
                ('operador', models.CharField(choices=[('gte', '≥ (mayor o igual)'), ('lte', '≤ (menor o igual)')], default='gte', help_text='Ignorado para "Sin heartbeat" (siempre es "más de X minutos").', max_length=3)),
                ('umbral', models.FloatField(help_text='% para CPU/RAM, ms para latencia, °C para temperatura, minutos para sin heartbeat.')),
                ('duracion_minutos', models.PositiveIntegerField(default=10, help_text='La condición debe sostenerse este tiempo antes de abrir la alerta (evita falsos positivos por un pico aislado).')),
                ('severidad', models.CharField(choices=[('warning', 'Advertencia'), ('critical', 'Crítica')], default='warning', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_alerta_creadas', to=settings.AUTH_USER_MODEL)),
                ('unidad_negocio', models.ForeignKey(blank=True, help_text='Vacío = regla global, aplica a todos los clientes. Con valor = solo ese cliente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas_alerta', to='catalogo.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Regla de alerta',
                'verbose_name_plural': 'Reglas de alerta',
                'db_table': 'regla_alerta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('reconocida', 'Reconocida'), ('resuelta', 'Resuelta')], default='abierta', max_length=10)),
                ('valor_disparador', models.FloatField(help_text='Valor de la métrica que confirmó la alerta.')),
                ('abierta_en', models.DateTimeField(auto_now_add=True)),
                ('reconocida_en', models.DateTimeField(blank=True, null=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='catalogo.estacion')),
                ('reconocida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='monitoreo.reglaalerta')),
            ],
            options={
                'db_table': 'alerta',
                'ordering': ['-abierta_en'],
            },
        ),
    ]
