# Generated by Django 5.2.16 on 2026-08-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_reglaalerta_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglaalerta',
            name='metrica',
            field=models.CharField(choices=[('cpu_carga_pct', 'CPU (%)'), ('ram_usada_pct', 'RAM (%)'), ('latencia_ms', 'Latencia (ms)'), ('temperatura_c', 'Temperatura (°C)'), ('sin_heartbeat', 'Sin heartbeat (minutos)'), ('bitlocker_deshabilitado', 'BitLocker deshabilitado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reglaalerta',
            name='operador',
            field=models.CharField(choices=[('gte', '≥ (mayor o igual)'), ('lte', '≤ (menor o igual)')], default='gte', help_text='Ignorado para "Sin heartbeat" (siempre "más de X minutos") y para "BitLocker deshabilitado" (condición binaria, no hay umbral que comparar).', max_length=3),
        ),
        migrations.AlterField(
            model_name='reglaalerta',
            name='umbral',
            field=models.FloatField(default=0, help_text='% para CPU/RAM, ms para latencia, °C para temperatura, minutos para sin heartbeat. Ignorado (dejar en 0) para "BitLocker deshabilitado".'),
        ),
    ]
