# Generated by Django 5.2.16 on 2026-08-14 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_estacion_windows_update_ultimo_error'),
        ('monitoreo', '0004_alter_reglaalerta_metrica_alter_reglaalerta_operador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglaalerta',
            name='metrica',
            field=models.CharField(choices=[('cpu_carga_pct', 'CPU (%)'), ('ram_usada_pct', 'RAM (%)'), ('latencia_ms', 'Latencia (ms)'), ('temperatura_c', 'Temperatura (°C)'), ('sin_heartbeat', 'Sin heartbeat (minutos)'), ('bitlocker_deshabilitado', 'BitLocker deshabilitado'), ('agente_caido_red_viva', 'Agente sin reportar (con red viva)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reglaalerta',
            name='operador',
            field=models.CharField(choices=[('gte', '≥ (mayor o igual)'), ('lte', '≤ (menor o igual)')], default='gte', help_text='Ignorado para "Sin heartbeat"/"Agente sin reportar (con red viva)" (siempre "más de X minutos") y para "BitLocker deshabilitado" (condición binaria, sin umbral).', max_length=3),
        ),
        migrations.AlterField(
            model_name='reglaalerta',
            name='umbral',
            field=models.FloatField(default=0, help_text='% para CPU/RAM, ms para latencia, °C para temperatura, minutos para sin heartbeat y para "Agente sin reportar (con red viva)". Ignorado (dejar en 0) para "BitLocker deshabilitado".'),
        ),
        migrations.CreateModel(
            name='EstadoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('mqtt', 'Agente MQTT'), ('meshcentral', 'MeshCentral')], max_length=20)),
                ('en_linea', models.BooleanField()),
                ('detalle', models.JSONField(blank=True, default=dict, help_text='Payload específico de la fuente (ej. conn de MeshCentral). No forma parte del contrato del cruce — solo referencia/debug.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_dispositivo', to='catalogo.estacion')),
            ],
            options={
                'verbose_name': 'Estado de dispositivo',
                'verbose_name_plural': 'Estados de dispositivo',
                'db_table': 'estado_dispositivo',
                'ordering': ['estacion__codigo', 'fuente'],
                'unique_together': {('estacion', 'fuente')},
            },
        ),
        migrations.CreateModel(
            name='EventoMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('mqtt', 'Agente MQTT'), ('meshcentral', 'MeshCentral')], max_length=20)),
                ('en_linea', models.BooleanField()),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_monitoreo', to='catalogo.estacion')),
            ],
            options={
                'db_table': 'evento_monitoreo',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['estacion', '-timestamp'], name='evento_moni_estacio_51c459_idx')],
            },
        ),
    ]
