# Generated by Django 5.2.16 on 2026-08-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0006_hypertable_evento_monitoreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestrametrica',
            name='disco_libre_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muestrametrica',
            name='disco_total_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reglaalerta',
            name='metrica',
            field=models.CharField(choices=[('cpu_carga_pct', 'CPU (%)'), ('ram_usada_pct', 'RAM (%)'), ('disco_usado_pct', 'Disco usado (%)'), ('latencia_ms', 'Latencia (ms)'), ('temperatura_c', 'Temperatura (°C)'), ('sin_heartbeat', 'Sin heartbeat (minutos)'), ('bitlocker_deshabilitado', 'BitLocker deshabilitado'), ('agente_caido_red_viva', 'Agente sin reportar (con red viva)')], max_length=30),
        ),
    ]
