# Generated by Django 5.2.16 on 2026-08-17 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_estacion_power_plan_actual_and_more'),
        ('monitoreo', '0007_muestrametrica_disco_libre_gb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglaalerta',
            name='metrica',
            field=models.CharField(choices=[('cpu_carga_pct', 'CPU (%)'), ('ram_usada_pct', 'RAM (%)'), ('disco_usado_pct', 'Disco usado (%)'), ('latencia_ms', 'Latencia (ms)'), ('temperatura_c', 'Temperatura (°C)'), ('sin_heartbeat', 'Sin heartbeat (minutos)'), ('bitlocker_deshabilitado', 'BitLocker deshabilitado'), ('agente_caido_red_viva', 'Agente sin reportar (con red viva)'), ('pos_errores', 'Errores del POS (por ventana de reporte)')], max_length=30),
        ),
        migrations.CreateModel(
            name='PosErrorDetectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=500)),
                ('nivel', models.CharField(default='ERROR', max_length=10)),
                ('cantidad_total', models.PositiveIntegerField(default=0)),
                ('primera_vez', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_errores', to='catalogo.estacion')),
            ],
            options={
                'verbose_name': 'Error del POS detectado',
                'verbose_name_plural': 'Errores del POS detectados',
                'db_table': 'pos_error_detectado',
                'ordering': ['-ultima_vez'],
                'unique_together': {('estacion', 'mensaje')},
            },
        ),
    ]
