# Generated by Django 5.2.16 on 2026-08-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0008_alter_reglaalerta_metrica_poserrordetectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='poserrordetectado',
            name='categoria',
            field=models.CharField(choices=[('sistema', 'Sistema (cuenta para la alerta)'), ('negocio', 'Negocio (no cuenta para la alerta)')], default='sistema', max_length=10),
        ),
    ]
