# Generated by Django 5.2.16 on 2026-08-18 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_estacion_power_plan_actual_and_more'),
        ('monitoreo', '0009_poserrordetectado_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentanaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino_tipo', models.CharField(choices=[('cadena', 'Toda la cadena'), ('grupos', 'Grupos específicos'), ('farmacias', 'Farmacias específicas'), ('estaciones', 'Estaciones específicas')], max_length=20)),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('motivo', models.CharField(help_text='Ej. "despliegue de POS v5.2 a toda la cadena".', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventanas_mantenimiento_creadas', to=settings.AUTH_USER_MODEL)),
                ('estaciones', models.ManyToManyField(blank=True, related_name='ventanas_mantenimiento', to='catalogo.estacion')),
                ('farmacias', models.ManyToManyField(blank=True, related_name='ventanas_mantenimiento', to='catalogo.farmacia')),
                ('grupos', models.ManyToManyField(blank=True, related_name='ventanas_mantenimiento', to='catalogo.grupo')),
                ('unidad_negocio', models.ForeignKey(help_text='Cliente al que se dirige. "Toda la cadena" significa toda la cadena de esta unidad de negocio, nunca de otras.', on_delete=django.db.models.deletion.PROTECT, related_name='ventanas_mantenimiento', to='catalogo.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Ventana de mantenimiento',
                'verbose_name_plural': 'Ventanas de mantenimiento',
                'db_table': 'ventana_mantenimiento',
                'ordering': ['-desde'],
            },
        ),
    ]
