# Generated by Django 5.2.16 on 2026-08-18 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_estacion_power_plan_actual_and_more'),
        ('monitoreo', '0010_ventanamantenimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='escalada_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se reenvió la notificación por seguir ABIERTA sin reconocer (ver apps.monitoreo.services.escalar_alertas_abiertas). Evita reescalar en cada corrida.', null=True),
        ),
        migrations.CreateModel(
            name='CanalNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('webhook_teams', 'Webhook de Microsoft Teams')], default='webhook_teams', max_length=20)),
                ('destino', models.URLField(help_text='URL del webhook entrante de Teams.')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canales_notificacion_creados', to=settings.AUTH_USER_MODEL)),
                ('unidad_negocio', models.ForeignKey(blank=True, help_text='Vacío = canal global, aplica a toda unidad de negocio que no tenga uno propio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canales_notificacion', to='catalogo.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Canal de notificación',
                'verbose_name_plural': 'Canales de notificación',
                'db_table': 'canal_notificacion',
                'ordering': ['unidad_negocio__codigo', 'tipo'],
            },
        ),
    ]
