# Generated by Django 5.2.16 on 2026-08-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0011_alerta_escalada_en_canalnotificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestrametrica',
            name='red_enviado_kbps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muestrametrica',
            name='red_recibido_kbps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reglaalerta',
            name='metrica',
            field=models.CharField(choices=[('cpu_carga_pct', 'CPU (%)'), ('ram_usada_pct', 'RAM (%)'), ('disco_usado_pct', 'Disco usado (%)'), ('latencia_ms', 'Latencia (ms)'), ('temperatura_c', 'Temperatura (°C)'), ('red_total_kbps', 'Red (KB/s)'), ('sin_heartbeat', 'Sin heartbeat (minutos)'), ('bitlocker_deshabilitado', 'BitLocker deshabilitado'), ('agente_caido_red_viva', 'Agente sin reportar (con red viva)'), ('pos_errores', 'Errores del POS (por ventana de reporte)')], max_length=30),
        ),
    ]
