# Generated by Django 5.2.16 on 2026-08-20 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_farmacia_ip_router'),
        ('monitoreo', '0012_muestrametrica_red_enviado_kbps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuestraRedFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_recibidos', models.BigIntegerField()),
                ('bytes_enviados', models.BigIntegerField()),
                ('red_recibido_kbps', models.FloatField(blank=True, null=True)),
                ('red_enviado_kbps', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras_red', to='catalogo.farmacia')),
            ],
            options={
                'verbose_name': 'Muestra de red de farmacia',
                'verbose_name_plural': 'Muestras de red de farmacia',
                'db_table': 'muestra_red_farmacia',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['farmacia', '-timestamp'], name='muestra_red_farmaci_567376_idx')],
            },
        ),
    ]
