# Generated by Django 5.2.16 on 2026-08-28 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0014_alter_mantenimiento_tipo_origen'),
        ('monitoreo', '0013_muestraredfarmacia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='mantenimiento',
            field=models.ForeignKey(blank=True, help_text='Mantenimiento abierto automáticamente por esta alerta, si la regla lo pide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_origen', to='mantenimiento.mantenimiento'),
        ),
        migrations.AddField(
            model_name='reglaalerta',
            name='abre_mantenimiento',
            field=models.BooleanField(default=False, help_text='Si al dispararse esta regla se abre automáticamente un mantenimiento para el equipo de la estación afectada.'),
        ),
    ]
