# Generated by Django 5.2.16 on 2026-09-12 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0026_farmacia_circuito_proveedor'),
        ('monitoreo', '0014_alerta_mantenimiento_reglaalerta_abre_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEnlaceFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcanzable', models.BooleanField(blank=True, help_text='True = respondió el último sondeo. False = caído (superó el umbral de fallas). null = nunca se sondeó todavía, que no es lo mismo que caído.', null=True)),
                ('latencia_ms', models.FloatField(blank=True, help_text='Latencia del último sondeo exitoso. null = el último falló.', null=True)),
                ('fallas_consecutivas', models.PositiveIntegerField(default=0)),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True)),
                ('ultimo_cambio_estado', models.DateTimeField(blank=True, help_text='Cuándo pasó de alcanzable a caído o viceversa. Sirve para "lleva N horas caída" sin tener que recorrer los eventos.', null=True)),
                ('farmacia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_enlace', to='catalogo.farmacia')),
            ],
            options={
                'verbose_name': 'Estado de enlace de farmacia',
                'verbose_name_plural': 'Estados de enlace de farmacia',
                'db_table': 'estado_enlace_farmacia',
                'ordering': ['farmacia__codigo'],
            },
        ),
        migrations.CreateModel(
            name='EventoEnlaceFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('circuito_proveedor', models.CharField(blank=True, help_text='Copia del circuito al momento de la caída. Es lo que el proveedor pide al abrir el ticket, y se guarda acá para que el evento siga siendo útil aunque la farmacia cambie de circuito después.', max_length=80)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_enlace', to='catalogo.farmacia')),
            ],
            options={
                'verbose_name': 'Caída de enlace',
                'verbose_name_plural': 'Caídas de enlace',
                'db_table': 'evento_enlace_farmacia',
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['farmacia', '-inicio'], name='evento_enla_farmaci_ea4d0c_idx')],
            },
        ),
    ]
