# Generated by Django 5.2.16 on 2026-09-12 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0015_estadoenlacefarmacia_eventoenlacefarmacia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoenlacefarmacia',
            options={'ordering': ['farmacia__codigo'], 'permissions': [('registrar_sondeo_enlace', 'Puede reportar resultados de sondeo de enlaces por API')], 'verbose_name': 'Estado de enlace de farmacia', 'verbose_name_plural': 'Estados de enlace de farmacia'},
        ),
    ]
