# Generated by Django 5.2.16 on 2026-09-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0016_alter_estadoenlacefarmacia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglaalerta',
            name='metrica',
            field=models.CharField(choices=[('cpu_carga_pct', 'CPU (%)'), ('ram_usada_pct', 'RAM (%)'), ('disco_usado_pct', 'Disco usado (%)'), ('latencia_ms', 'Latencia (ms)'), ('temperatura_c', 'Temperatura (°C)'), ('red_total_kbps', 'Red (kbps)'), ('sin_heartbeat', 'Sin heartbeat (minutos)'), ('bitlocker_deshabilitado', 'BitLocker deshabilitado'), ('agente_caido_red_viva', 'Agente sin reportar (con red viva)'), ('pos_errores', 'Errores del POS (por ventana de reporte)')], max_length=30),
        ),
    ]
