# Generated by Django 5.2.16 on 2026-09-15 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0027_estacion_desfase_reloj_segundos_and_more'),
        ('monitoreo', '0017_alter_reglaalerta_metrica'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoBordeFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, help_text='Tal como lo reporta sysDescr, ej. "RouterOS RB951Ui-2nD".', max_length=120)),
                ('numero_serie', models.CharField(blank=True, max_length=60)),
                ('version_routeros', models.CharField(blank=True, max_length=30)),
                ('nombre_sistema', models.CharField(blank=True, help_text='sysName del equipo. Normalmente es el código de la farmacia: si no coincide, la IP cargada apunta a otro equipo (ver `nombre_coincide`).', max_length=60)),
                ('uptime_segundos', models.BigIntegerField(blank=True, help_text='Hace cuánto arrancó el equipo. Se guarda en segundos aunque SNMP lo entregue en centésimas, para no obligar a dividir en cada lectura.', null=True)),
                ('ultima_lectura', models.DateTimeField(blank=True, null=True)),
                ('farmacia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_borde', to='catalogo.farmacia')),
            ],
            options={
                'verbose_name': 'Equipo de borde de farmacia',
                'verbose_name_plural': 'Equipos de borde de farmacia',
                'db_table': 'equipo_borde_farmacia',
                'ordering': ['farmacia__codigo'],
            },
        ),
    ]
