# Generated by Django 5.2.16 on 2026-09-15 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0027_estacion_desfase_reloj_segundos_and_more'),
        ('monitoreo', '0018_equipobordefarmacia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoDetectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(help_text='Normalizada a AA:BB:CC:DD:EE:FF, como `Activo.mac`.', max_length=17)),
                ('ip', models.GenericIPAddressField()),
                ('interfaz_indice', models.PositiveIntegerField(blank=True, help_text='ifIndex del puerto del router donde se lo vio. Cruzado con el nombre de la interfaz (ej. "ether4_BASE") dice en qué puerto está enchufado.', null=True)),
                ('visto_por_primera_vez', models.DateTimeField(auto_now_add=True)),
                ('visto_por_ultima_vez', models.DateTimeField()),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_detectados', to='catalogo.farmacia')),
            ],
            options={
                'verbose_name': 'Dispositivo detectado',
                'verbose_name_plural': 'Dispositivos detectados',
                'db_table': 'dispositivo_detectado',
                'ordering': ['farmacia__codigo', 'ip'],
                'indexes': [models.Index(fields=['farmacia', 'ip'], name='dispositivo_farmaci_abd5ab_idx')],
                'constraints': [models.UniqueConstraint(fields=('farmacia', 'mac'), name='un_dispositivo_por_mac_y_farmacia')],
            },
        ),
    ]
