# Generated by Django 5.2.16 on 2026-09-15 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0028_farmacia_ancho_contratado_mbps'),
        ('monitoreo', '0019_dispositivodetectado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinicioEquipoBorde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detectado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('arranque_estimado', models.DateTimeField(help_text='Cuándo arrancó el equipo, calculado como el momento de la lectura menos su uptime. Es estimado porque entre el arranque real y la lectura pasa lo que tarde el sondeo en llegar.')),
                ('uptime_previo_segundos', models.BigIntegerField(blank=True, help_text='Cuánto llevaba encendido en la lectura anterior. Un valor alto seguido de un reinicio es un equipo estable que se cayó una vez; valores bajos repetidos son un equipo que se reinicia solo, que es el problema difícil de ver.', null=True)),
                ('version_routeros', models.CharField(blank=True, help_text='Versión al momento del reinicio: distingue un arranque tras una actualización de uno espontáneo.', max_length=30)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinicios_equipo', to='catalogo.farmacia')),
            ],
            options={
                'verbose_name': 'Reinicio de equipo de borde',
                'verbose_name_plural': 'Reinicios de equipo de borde',
                'db_table': 'reinicio_equipo_borde',
                'ordering': ['-detectado_en'],
                'indexes': [models.Index(fields=['farmacia', '-detectado_en'], name='reinicio_eq_farmaci_40a54f_idx')],
            },
        ),
    ]
