# Generated by Django 5.2.16 on 2026-09-16 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0024_activo_slot_alter_activo_tipo_and_more'),
        ('catalogo', '0029_hmac_por_estacion'),
        ('monitoreo', '0021_hypertable_muestra_red_farmacia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoRedActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_sondeada', models.GenericIPAddressField(help_text='La IP que se pingeó. Se guarda porque la del activo puede cambiar y entonces este estado ya no habla del mismo destino.')),
                ('responde', models.BooleanField(default=False)),
                ('latencia_ms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ultima_verificacion', models.DateTimeField()),
                ('ultima_respuesta', models.DateTimeField(blank=True, help_text='La última vez que contestó. Vacío = nunca contestó desde que se lo monitorea, que no es lo mismo que "se cayó recién".', null=True)),
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_red', to='activos.activo')),
                ('estacion_que_sondeo', models.ForeignKey(blank=True, help_text='Qué estación hizo el ping. Si esa estación se apaga, el activo deja de sondearse — y eso explica un "sin verificar" que si no parecería una caída.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sondeos_activos', to='catalogo.estacion')),
            ],
            options={
                'verbose_name': 'Estado de red de un activo',
                'verbose_name_plural': 'Estados de red de activos',
                'db_table': 'estado_red_activo',
                'ordering': ['activo__codigo'],
            },
        ),
    ]
