# Generated by Django 5.2.16 on 2026-09-17 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0030_hmac_propio_confirmado'),
        ('monitoreo', '0022_estado_red_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglaalerta',
            name='metrica',
            field=models.CharField(choices=[('cpu_carga_pct', 'CPU (%)'), ('ram_usada_pct', 'RAM (%)'), ('disco_usado_pct', 'Disco usado (%)'), ('latencia_ms', 'Latencia (ms)'), ('temperatura_c', 'Temperatura (°C)'), ('red_total_kbps', 'Red (kbps)'), ('sin_heartbeat', 'Sin heartbeat (minutos)'), ('bitlocker_deshabilitado', 'BitLocker deshabilitado'), ('agente_caido_red_viva', 'Agente sin reportar (con red viva)'), ('pos_errores', 'Errores del POS (por ventana de reporte)'), ('servicio_pos_caido', 'Servicio del POS sin responder')], max_length=30),
        ),
        migrations.CreateModel(
            name='EstadoServicioPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('pg_local', 'PostgreSQL local'), ('pg_central', 'PostgreSQL central'), ('odoo', 'Odoo'), ('recargas_soap', 'Web service de recargas')], max_length=20)),
                ('disponible', models.BooleanField(default=False)),
                ('latencia_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('mensaje', models.CharField(blank=True, help_text='Lo que contestó el servicio: la versión de PostgreSQL, el código HTTP, o el error tal cual. Crudo, para poder diagnosticar sin entrar al equipo.', max_length=300)),
                ('endpoint', models.CharField(blank=True, help_text='A qué se apuntó (host:puerto/base o URL). NUNCA lleva credenciales: mismo criterio que EstadoRedActivo, que guarda la IP sondeada y nada más.', max_length=200)),
                ('critico', models.BooleanField(default=True, help_text='Si sin este servicio la caja no puede vender. Decide si la regla de alerta que se dispara es crítica o una advertencia.')),
                ('ultima_verificacion', models.DateTimeField()),
                ('ultima_respuesta', models.DateTimeField(blank=True, help_text='La última vez que contestó. Vacío = nunca contestó desde que se lo monitorea, que no es lo mismo que "se cayó recién".', null=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_pos', to='catalogo.estacion')),
            ],
            options={
                'verbose_name': 'Estado de un servicio del POS',
                'verbose_name_plural': 'Estados de los servicios del POS',
                'db_table': 'estado_servicio_pos',
                'ordering': ['estacion__codigo', 'servicio'],
                'constraints': [models.UniqueConstraint(fields=('estacion', 'servicio'), name='un_estado_por_estacion_y_servicio')],
            },
        ),
        migrations.CreateModel(
            name='MuestraServicioPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('pg_local', 'PostgreSQL local'), ('pg_central', 'PostgreSQL central'), ('odoo', 'Odoo'), ('recargas_soap', 'Web service de recargas')], max_length=20)),
                ('latencia_ms', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras_servicios_pos', to='catalogo.estacion')),
            ],
            options={
                'verbose_name': 'Muestra de un servicio del POS',
                'verbose_name_plural': 'Muestras de los servicios del POS',
                'db_table': 'muestra_servicio_pos',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['estacion', 'servicio', '-timestamp'], name='muestra_ser_estacio_be9f3b_idx')],
            },
        ),
    ]
