# Generated by Django 5.2.16 on 2026-09-17 21:22

from django.db import migrations, models
from django.utils import timezone


def marcar_historico_como_ya_avisado(apps, schema_editor):
    """Todo lo que ya pasó queda marcado como avisado, sin mandar nada.

    Al desplegar esto había 940 eventos, 162 de ellos abiertos y 134 con más de 24
    horas de caída. Sin este backfill, la primera corrida de
    `notificar_cambios_enlaces` habría mandado un correo con las 162 de golpe — y las
    crónicas no son novedad para nadie, solo ruido que entierra la caída de hoy.

    El aviso empieza a contar desde el despliegue: lo que ya estaba caído se revisa por
    el panel, no por correo.
    """
    Evento = apps.get_model('monitoreo', 'EventoEnlaceFarmacia')
    ahora = timezone.now()
    Evento.objects.filter(notificado_en__isnull=True).update(notificado_en=ahora)
    Evento.objects.filter(fin__isnull=False, recuperacion_notificada_en__isnull=True).update(
        recuperacion_notificada_en=ahora,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0023_servicios_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoenlacefarmacia',
            name='notificado_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se avisó por correo de esta caída. Vacío = todavía no se avisó.', null=True),
        ),
        migrations.AddField(
            model_name='eventoenlacefarmacia',
            name='recuperacion_notificada_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se avisó de que el enlace volvió. Vacío = todavía no se avisó.', null=True),
        ),
        migrations.RunPython(marcar_historico_como_ya_avisado, migrations.RunPython.noop),
    ]
