# Generated by Django 5.2.16 on 2026-09-17 21:44

from django.db import migrations, models


def marcar_las_que_ya_respondieron(apps, schema_editor):
    """Rellena `respondio_alguna_vez` con lo que ya se sabe del historico.

    Dos evidencias, y alcanza con cualquiera: que el enlace este arriba AHORA, o que
    tenga una caida ya cerrada (si se cerro, en algun momento volvio a responder).

    Lo que queda en False es justo lo que se buscaba aislar: al aplicar esto habia 133
    farmacias en ese grupo, todas con la caida abierta desde el mismo instante en que
    arranco el monitoreo (11-sep-2026 22:00). Nunca respondieron un solo sondeo, asi
    que no son caidas que reportarle al proveedor.
    """
    Estado = apps.get_model('monitoreo', 'EstadoEnlaceFarmacia')
    Evento = apps.get_model('monitoreo', 'EventoEnlaceFarmacia')

    Estado.objects.filter(alcanzable=True).update(respondio_alguna_vez=True)
    con_caida_cerrada = Evento.objects.filter(fin__isnull=False).values_list('farmacia_id', flat=True).distinct()
    Estado.objects.filter(farmacia_id__in=list(con_caida_cerrada)).update(respondio_alguna_vez=True)


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0024_notificacion_enlaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoenlacefarmacia',
            name='respondio_alguna_vez',
            field=models.BooleanField(default=False, help_text='False y alcanzable=False = nunca respondio desde que se lo sondea, que no es una caida: revisar ruta, IP cargada o si el sitio sigue activo.'),
        ),
        migrations.RunPython(marcar_las_que_ya_respondieron, migrations.RunPython.noop),
    ]
