# Generated by Django 5.2.16 on 2026-09-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0025_nunca_respondio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='diagnostico_generado_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se generó el diagnóstico. Vacío = no se pidió o no se pudo generar. Marca que el intento ya ocurrió, para no repetir la llamada (y el costo).', null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='diagnostico_ia',
            field=models.TextField(blank=True, help_text='Diagnóstico automático generado por IA. Es una hipótesis sin verificar: confirmar antes de actuar.', null=True),
        ),
        migrations.AlterField(
            model_name='canalnotificacion',
            name='destino',
            field=models.CharField(help_text='URL del webhook entrante (Teams) o chat_id del chat/grupo (Telegram).', max_length=500),
        ),
        migrations.AlterField(
            model_name='canalnotificacion',
            name='tipo',
            field=models.CharField(choices=[('webhook_teams', 'Webhook de Microsoft Teams'), ('telegram', 'Telegram (chat_id)')], default='webhook_teams', max_length=20),
        ),
    ]
