# Generated by Django 5.2.16 on 2026-09-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0026_telegram_y_diagnostico_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoenlacefarmacia',
            name='primer_fallo',
            field=models.DateTimeField(blank=True, help_text='Primer sondeo fallido de la racha actual. Se limpia cuando responde.', null=True),
        ),
    ]
