# Generated by Django 5.2.16 on 2026-09-19 00:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0027_primer_fallo_enlace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_minimos_aviso_enlace', models.PositiveSmallIntegerField(default=10, help_text='Un enlace que se cae y vuelve en menos de esto no genera aviso. Si sigue caído en la corrida siguiente, ahí sí se avisa: no se pierde, se espera. 0 = avisar toda caída confirmada.', verbose_name='Minutos mínimos antes de avisar una caída de enlace')),
                ('fallas_consecutivas_enlace', models.PositiveSmallIntegerField(default=3, help_text='Con el barrido cada 2 minutos, 3 equivalen a ~6 minutos de fallos antes de declarar la caída. Bajarlo a 1 haría que un paquete ICMP perdido —que pasa seguido en enlaces WAN— cuente como caída.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Sondeos fallidos seguidos para declarar caído un enlace')),
                ('minutos_escalamiento_alerta', models.PositiveSmallIntegerField(default=30, help_text='Una alerta que sigue ABIERTA y sin reconocer pasado este tiempo se vuelve a notificar por los mismos canales. Reconocerla detiene el reenvío aunque no se haya resuelto.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minutos sin reconocer antes de reenviar una alerta')),
                ('dias_ventana_top_errores', models.PositiveSmallIntegerField(default=7, help_text='El ranking de errores del POS solo muestra los vistos en esta ventana. Sin corte, un problema resuelto hace semanas sigue encabezando, porque el contador de cada mensaje es de por vida.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Días que mira /toperrores hacia atrás')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Quién tocó estos valores por última vez. Un umbral cambiado explica por qué el sistema empezó a avisar más o menos que antes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del monitoreo',
                'verbose_name_plural': 'Configuración del monitoreo',
                'db_table': 'configuracion_monitoreo',
            },
        ),
    ]
