# Generated by Django 5.2.16 on 2026-09-19 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0030_hmac_propio_confirmado'),
        ('monitoreo', '0028_configuracion_monitoreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoenlacefarmacia',
            name='farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_enlace', to='catalogo.farmacia'),
        ),
    ]
