# Generated by Django 5.2.16 on 2026-09-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0030_metrica_desfase_reloj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioPosMonitoreado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(help_text='Identificador corto y estable (ej. "balanza", "facturacion"). Es lo que viaja en cada reporte del agente y lo que guarda EstadoServicioPos.servicio, así que cambiarlo después desconecta el historial ya acumulado. Máximo 20 caracteres.', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Cómo se lee en el panel y en la alerta, ej. "Balanza electrónica".', max_length=100)),
                ('tipo', models.CharField(choices=[('ping', 'Ping (ICMP)'), ('http', 'HTTP/HTTPS'), ('postgres', 'PostgreSQL')], default='ping', max_length=10)),
                ('origen', models.CharField(choices=[('config_pos', 'Descubierto del .exe.Config del POS'), ('catalogo', 'Definido acá, con destino fijo')], default='catalogo', help_text='"Descubierto" = el agente lo encuentra en el .exe.Config de su POS y el destino de abajo se ignora. "Definido acá" = se chequea el destino que diga esta fila, igual en todas las estaciones.', max_length=12)),
                ('destino', models.CharField(blank=True, help_text='IP, hostname o URL completa según el tipo: "192.168.102.201" para ping, "http://192.168.102.201:8080/estado" para HTTP, "192.168.102.201" para PostgreSQL (la base va en el campo de abajo). NUNCA credenciales: esto se publica a la flota y se guarda en EstadoServicioPos.endpoint, que es visible en el panel.', max_length=200)),
                ('puerto', models.PositiveIntegerField(blank=True, help_text='Solo para PostgreSQL (5432 si se deja vacío). Ping no usa puerto y en HTTP va dentro de la URL.', null=True)),
                ('base_datos', models.CharField(blank=True, help_text='Solo para PostgreSQL: contra qué base correr el SELECT 1.', max_length=100)),
                ('critico', models.BooleanField(default=False, help_text='Si sin este servicio la caja NO puede vender. Decide si la alerta que se abre es crítica o una advertencia: es el mismo campo que ya usa evaluar_regla_servicio_pos. Por defecto NO crítico — que una caja no pueda pesar es molesto, que no pueda cobrar es otra cosa.')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar deja de pedirle el chequeo al agente y NO borra nada: los EstadoServicioPos y MuestraServicioPos ya acumulados quedan intactos para poder mirar el historial.')),
                ('nota', models.TextField(blank=True, help_text='Para quien atiende la alerta: por qué importa este servicio, a quién avisar, qué mirar primero. Nunca credenciales.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio del POS monitoreado',
                'verbose_name_plural': 'Catálogo de servicios del POS monitoreados',
                'db_table': 'servicio_pos_monitoreado',
                'ordering': ['-critico', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='estadoserviciopos',
            name='servicio',
            field=models.CharField(help_text='Clave del ServicioPosMonitoreado que se chequeo. Texto y no ForeignKey a proposito: dar de baja una entrada del catalogo no puede dejar huerfano el historial ya acumulado.', max_length=20),
        ),
        migrations.AlterField(
            model_name='muestraserviciopos',
            name='servicio',
            field=models.CharField(help_text='Clave del ServicioPosMonitoreado que se chequeo. Texto y no ForeignKey a proposito: dar de baja una entrada del catalogo no puede dejar huerfano el historial ya acumulado.', max_length=20),
        ),
    ]
