# Generated by Django 5.2.16 on 2026-09-21 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0030_hmac_propio_confirmado'),
        ('monitoreo', '0032_sembrar_catalogo_servicios_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglaalerta',
            name='metrica',
            field=models.CharField(choices=[('cpu_carga_pct', 'CPU (%)'), ('ram_usada_pct', 'RAM (%)'), ('disco_usado_pct', 'Disco usado (%)'), ('latencia_ms', 'Latencia (ms)'), ('temperatura_c', 'Temperatura (°C)'), ('red_total_kbps', 'Red (kbps)'), ('sin_heartbeat', 'Sin heartbeat (minutos)'), ('bitlocker_deshabilitado', 'BitLocker deshabilitado'), ('agente_caido_red_viva', 'Agente sin reportar (con red viva)'), ('pos_errores', 'Errores del POS (por ventana de reporte)'), ('servicio_pos_caido', 'Servicio del POS sin responder'), ('desfase_reloj', 'Desfase de reloj (segundos)'), ('evento_sistema', 'Evento de Windows (disco, apagon...)')], max_length=30),
        ),
        migrations.CreateModel(
            name='EventoSistemaVigilado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.PositiveIntegerField(help_text='El número que muestra el visor de Windows, ej. 41 para el apagón inesperado o 1000 para el crash de una aplicación.', verbose_name='ID del evento')),
                ('log', models.CharField(choices=[('System', 'System'), ('Application', 'Application')], default='System', help_text='En qué registro vive. El mismo número puede significar cosas distintas en System y en Application.', max_length=20)),
                ('proveedor', models.CharField(help_text='Quién emite el evento, ej. "disk", "Ntfs", "Microsoft-Windows-Kernel-Power". OBLIGATORIO, y no es un detalle: el ID solo NO identifica un evento. Medido el 20-sep-2026 contra un visor real, el ID 55 de System devolvió 260 avisos de "Kernel-Processor-Power" (administración de energía del procesador) cuando se esperaba corrupción de NTFS, y el 153 devolvió "Kernel-Boot" en vez de reintentos de disco. Filtrar solo por número recolecta otra cosa y nadie se entera.', max_length=120)),
                ('nombre', models.CharField(help_text='Cómo se lee en el panel, ej. "Apagón inesperado". El texto crudo de Windows es largo y en inglés.', max_length=120)),
                ('severidad', models.CharField(choices=[('warning', 'Advertencia'), ('critical', 'Crítica')], default='warning', max_length=10)),
                ('abre_alerta', models.BooleanField(default=False, help_text='Si además de guardarse dispara una alerta. Por defecto NO: con 260 eventos de un solo tipo en una sola máquina, alertar por todo es cómo se consigue que dejen de mirarse las alertas.')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar deja de pedírselo al agente y NO borra el historial ya recolectado.')),
                ('nota', models.TextField(blank=True, help_text='Para quien atiende: qué significa este evento y qué mirar primero.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento de Windows vigilado',
                'verbose_name_plural': 'Catálogo de eventos de Windows vigilados',
                'db_table': 'evento_sistema_vigilado',
                'ordering': ['-abre_alerta', 'log', 'identificador'],
                'constraints': [models.UniqueConstraint(fields=('log', 'proveedor', 'identificador'), name='un_evento_por_log_proveedor_e_id')],
            },
        ),
        migrations.CreateModel(
            name='EventoSistemaDetectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=20)),
                ('identificador', models.PositiveIntegerField(verbose_name='ID del evento')),
                ('origen', models.CharField(help_text='El proveedor que lo emitió, ej. "Microsoft-Windows-Kernel-Power". Parte de la clave, no un adorno: el mismo ID significa cosas distintas según quién lo emita (ver el help_text de EventoSistemaVigilado.proveedor).', max_length=120)),
                ('ultimo_mensaje', models.CharField(blank=True, help_text='El texto del evento más reciente de este tipo, recortado. Crudo, para poder diagnosticar sin entrar al equipo.', max_length=500)),
                ('cantidad_total', models.PositiveIntegerField(default=0)),
                ('primera_vez', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_sistema', to='catalogo.estacion')),
            ],
            options={
                'verbose_name': 'Evento de Windows detectado',
                'verbose_name_plural': 'Eventos de Windows detectados',
                'db_table': 'evento_sistema_detectado',
                'ordering': ['-ultima_vez'],
                'indexes': [models.Index(fields=['estacion', '-ultima_vez'], name='evento_sist_estacio_00ff1f_idx')],
                'constraints': [models.UniqueConstraint(fields=('estacion', 'log', 'origen', 'identificador'), name='un_evento_de_sistema_por_estacion_y_tipo')],
            },
        ),
    ]
