"""Las cuatro series dejan de usar `auto_now_add` para su `timestamp`.

No cambia nada en la base —`default` y `editable` son de Python, no del esquema— y se
genera igual porque el estado de las migraciones tiene que seguir al de los modelos.

El motivo está en 0035: convertidas en hypertables, TimescaleDB rechaza un UPDATE que
mueva una fila a otro chunk. `auto_now_add` ignora cualquier fecha que se le pase al
crear, así que la única forma de fechar una fila era corregirla después — justo lo que
dejó de ser posible. Con `default=timezone.now` la fecha se elige en el INSERT y la
fila nace en el chunk que le toca.
"""
# Generated by Django 5.2.16 on 2026-09-21 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0035_hypertables_de_verdad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomonitoreo',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='muestrametrica',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='muestraredfarmacia',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='muestraserviciopos',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
