"""La otra mitad del freno: dejar de aceptar enrolamientos nuevos.

Pausar las estaciones ya enroladas no alcanza si el instalador sigue dando de alta
equipos que arrancan sin pausar. Un re-enrolamiento (estacion que perdio su
identidad.json) se sigue atendiendo: negarselo la dejaria muda sin que nadie lo pidiera.
"""
# Generated by Django 5.2.16 on 2026-09-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0036_timestamps_de_series_fechables'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmonitoreo',
            name='enrolamiento_habilitado',
            field=models.BooleanField(default=True, help_text='La otra mitad del freno de emergencia, y la que hay que apagar PRIMERO: pausar las estaciones ya enroladas no sirve de nada si el instalador sigue dando de alta equipos nuevos que arrancan sin pausar. Desactivarlo NO afecta a las estaciones existentes: un re-enrolamiento (una estación que perdió su identidad.json) se sigue atendiendo, porque negárselo la dejaría muda sin que nadie lo haya pedido.', verbose_name='Aceptar enrolamientos nuevos'),
        ),
    ]
