"""Nueva metrica: veces que una estacion se corrigio el reloj sola.

El umbral lo define una ReglaAlerta desde el panel y no el agente, por el mismo criterio
que el resto: fijarlo en el ejecutable obligaria a redistribuirlo a ~1.800 estaciones
para cambiar un numero.
"""
# Generated by Django 5.2.16 on 2026-09-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0037_interruptor_de_enrolamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglaalerta',
            name='metrica',
            field=models.CharField(choices=[('cpu_carga_pct', 'CPU (%)'), ('ram_usada_pct', 'RAM (%)'), ('disco_usado_pct', 'Disco usado (%)'), ('latencia_ms', 'Latencia (ms)'), ('temperatura_c', 'Temperatura (°C)'), ('red_total_kbps', 'Red (kbps)'), ('sin_heartbeat', 'Sin heartbeat (minutos)'), ('bitlocker_deshabilitado', 'BitLocker deshabilitado'), ('agente_caido_red_viva', 'Agente sin reportar (con red viva)'), ('pos_errores', 'Errores del POS (por ventana de reporte)'), ('servicio_pos_caido', 'Servicio del POS sin responder'), ('desfase_reloj', 'Desfase de reloj (segundos)'), ('evento_sistema', 'Evento de Windows (disco, apagon...)'), ('autocorrecciones_reloj', 'Veces que la estación se corrigió el reloj sola')], max_length=30),
        ),
    ]
