"""Índice (estado, -abierta_en) en `alerta`: la tabla no tenía ninguno propio.

Su Meta declaraba solo `db_table` y `ordering`, así que las seis consultas más frecuentes
del monitoreo —el contador del dashboard, los de `resumen_operacion`, el Centro de
Monitoreo, el listado del panel, el escalamiento y los comandos del bot— filtraban por
`estado` recorriendo la tabla y ordenando el resultado aparte.

El orden de los campos no es arbitrario: `estado` primero porque es la igualdad, y
`-abierta_en` después para que el índice ya entregue las filas ordenadas. El `ordering`
del Meta se aplica en TODAS las consultas del modelo, así que ese segundo campo es lo que
evita el sort.

Solo crea un índice: en el modelo quedó anotado qué otros se evaluaron y por qué NO se
agregaron (ver `Alerta.Meta.indexes`). A 1.300 farmacias la tabla que más escribe el
monitoreo no debe cargar índices que nadie aprovecha.

Es una operación de solo lectura sobre los datos: no modifica ni borra filas. En Postgres
un `CREATE INDEX` toma un lock de escritura sobre la tabla mientras lo construye; con el
tamaño actual de `alerta` eso es cuestión de segundos.
"""
# Generated by Django 5.2.16 on 2026-10-03 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0035_corp_admin_y_tipo_tienda'),
        ('mantenimiento', '0023_idempotencia_y_cierres_en_conflicto'),
        ('monitoreo', '0038_metrica_de_autocorrecciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['estado', '-abierta_en'], name='alerta_estado_9f3858_idx'),
        ),
    ]
