# Generated by Django 5.2.16 on 2026-10-10 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0028_activo_observaciones_activo_ubicacion'),
        ('catalogo', '0035_corp_admin_y_tipo_tienda'),
        ('monitoreo', '0041_quitar_indices_redundantes_de_prefijo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilSnmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Para qué familia de equipos es, ej. "Impresoras administrativas".', max_length=80, unique=True)),
                ('version', models.CharField(choices=[('2c', 'SNMP v2c')], default='2c', max_length=2)),
                ('comunidad_cifrada', models.TextField(blank=True, help_text='Token Fernet — nunca texto plano. Se carga con `asignar_comunidad()`.')),
                ('puerto', models.PositiveSmallIntegerField(default=161)),
                ('timeout_segundos', models.PositiveSmallIntegerField(default=3, help_text='3 s es lo que ya está validado contra equipos de producción en apps.monitoreo.mikrotik.')),
                ('reintentos', models.PositiveSmallIntegerField(default=1, help_text='1 y no 0 como los Mikrotik: una impresora en ahorro de energía tarda en despertar, y un router no duerme.')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('unidad_negocio', models.ForeignKey(blank=True, help_text='Vacío = perfil global, aplica a todos los clientes. Mismo criterio que ReglaAlerta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_snmp', to='catalogo.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Perfil SNMP',
                'verbose_name_plural': 'Perfiles SNMP',
                'db_table': 'perfil_snmp',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoSnmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.CharField(choices=[('IMPRESORA', 'Impresora (Printer-MIB)'), ('RED', 'Switch / router (IF-MIB)'), ('GENERICO', 'Genérico (solo identidad)')], default='GENERICO', help_text='Qué métricas pedirle. GENERICO sirve para descubrir qué es un equipo antes de clasificarlo.', max_length=20)),
                ('ip_sondeada', models.GenericIPAddressField(help_text='La IP que se sondeó. Se guarda aparte de `Activo.ip` porque la del activo puede cambiar, y entonces este estado habla de otro destino (mismo criterio que EstadoRedActivo.ip_sondeada).')),
                ('habilitado', models.BooleanField(default=True, help_text='Apagarlo deja de sondear sin perder el historial ni la configuración.')),
                ('ultima_lectura', models.DateTimeField(blank=True, help_text='Último intento, exitoso o no.', null=True)),
                ('ultimo_exito', models.DateTimeField(blank=True, help_text='Vacío = nunca respondió desde que se lo monitorea, que NO es lo mismo que "se cayó recién" (mismo criterio que EstadoRedActivo.ultima_respuesta).', null=True)),
                ('fallas_consecutivas', models.PositiveSmallIntegerField(default=0, help_text='Para el backoff: un equipo de baja no debe costar un timeout por ciclo para siempre.')),
                ('ultimo_error', models.CharField(blank=True, choices=[('timeout', 'Sin respuesta (timeout)'), ('sin_ruta', 'Sin ruta de red hasta el equipo'), ('snmp_sin_respuesta', 'Responde ping pero no SNMP'), ('posible_credencial', 'Posible community equivocada'), ('autenticacion', 'Fallo de autenticación (v3)'), ('sin_soporte', 'El equipo no publica estas métricas'), ('perfil_sin_comunidad', 'El perfil no tiene community cargada')], max_length=24)),
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_snmp', to='activos.activo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetivos', to='monitoreo.perfilsnmp')),
            ],
            options={
                'verbose_name': 'Objetivo SNMP',
                'verbose_name_plural': 'Objetivos SNMP',
                'db_table': 'objetivo_snmp',
                'ordering': ['activo__codigo'],
            },
        ),
        migrations.CreateModel(
            name='LecturaSnmpActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='La clave normalizada del catálogo: toner.black.nivel, paginas.total, bandeja.1.2.nivel. NUNCA un OID — el panel no tiene por qué saberlos.', max_length=60)),
                ('valor', models.FloatField(blank=True, help_text='Vacío = el equipo no pudo dar el dato. NO es lo mismo que cero.', null=True)),
                ('valor_crudo', models.IntegerField(blank=True, help_text='Lo que vino sin interpretar, incluidos los centinelas -1/-2/-3.', null=True)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('texto', models.CharField(blank=True, help_text='La descripción que da el equipo ("Tóner residual") o el texto de una alerta. Viene en español en varios modelos, que es más accionable que un enum.', max_length=200)),
                ('actualizado_en', models.DateTimeField()),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='monitoreo.objetivosnmp')),
            ],
            options={
                'verbose_name': 'Lectura SNMP actual',
                'verbose_name_plural': 'Lecturas SNMP actuales',
                'db_table': 'lectura_snmp_actual',
                'ordering': ['objetivo__activo__codigo', 'clave'],
                'constraints': [models.UniqueConstraint(fields=('objetivo', 'clave'), name='una_lectura_por_clave')],
            },
        ),
        migrations.AddIndex(
            model_name='objetivosnmp',
            index=models.Index(fields=['habilitado', 'ultima_lectura'], name='objetivo_snmp_pendientes'),
        ),
    ]
