# Generated by Django 5.2.16 on 2026-10-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0028_activo_observaciones_activo_ubicacion'),
        ('monitoreo', '0042_perfilsnmp_objetivosnmp_lecturasnmpactual_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='objetivosnmp',
            name='objetivo_snmp_pendientes',
        ),
        migrations.AddField(
            model_name='objetivosnmp',
            name='ultima_lectura_identidad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetivosnmp',
            name='ultima_lectura_lenta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetivosnmp',
            name='ultima_lectura_rapida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objetivosnmp',
            name='ultima_lectura',
            field=models.DateTimeField(blank=True, help_text='Último intento de CUALQUIER cadencia, exitoso o no. Es "cuándo supimos algo de este equipo por última vez"; para decidir a quién le toca se usan los tres de abajo.', null=True),
        ),
        migrations.AddIndex(
            model_name='objetivosnmp',
            index=models.Index(fields=['habilitado', 'ultima_lectura_rapida'], name='objetivo_snmp_pend_rapida'),
        ),
        migrations.AddIndex(
            model_name='objetivosnmp',
            index=models.Index(fields=['habilitado', 'ultima_lectura_lenta'], name='objetivo_snmp_pend_lenta'),
        ),
        migrations.AddIndex(
            model_name='objetivosnmp',
            index=models.Index(fields=['habilitado', 'ultima_lectura_identidad'], name='objetivo_snmp_pend_ident'),
        ),
    ]
