# Generated by Django 5.2.16 on 2026-07-17 20:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='El código de farmacia solo admite mayúsculas y números, ej. ML001', regex='^[A-Z0-9]+$')])),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observacion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Farmacias',
                'db_table': 'farmacia',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El código de grupo solo admite mayúsculas y números, ej. TRX001', regex='^[A-Z0-9]+$')])),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('version_objetivo', models.CharField(blank=True, help_text='Versión del POS que este grupo debería tener instalada.', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grupo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='El código de estación debe tener el formato FARMACIA-SUFIJO, ej. ML001-ADM', regex='^[A-Z0-9]+-[A-Z0-9]+$')])),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('so_nombre', models.CharField(blank=True, help_text='Ej. Windows 10, Windows 11', max_length=50)),
                ('so_build', models.CharField(blank=True, help_text='Ej. 19045 (22H2)', max_length=30)),
                ('version_agente', models.CharField(blank=True, max_length=30)),
                ('version_pos', models.CharField(blank=True, max_length=30)),
                ('estado_conexion', models.CharField(choices=[('nunca_conectada', 'Nunca conectada'), ('online', 'En línea'), ('offline', 'Fuera de línea')], default='nunca_conectada', max_length=20)),
                ('ultimo_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('token_enrolamiento', models.CharField(editable=False, max_length=64, unique=True)),
                ('estado_aprobacion', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estaciones', to='catalogo.farmacia')),
            ],
            options={
                'db_table': 'estacion',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='farmacia',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmacias', to='catalogo.grupo'),
        ),
    ]
