# Generated by Django 5.2.16 on 2026-07-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='hardware_id',
            field=models.CharField(blank=True, help_text='Identificador estable del equipo (MachineGuid de Windows). Se fija en el primer enrolamiento y se exige en los re-enrolamientos para evitar suplantación.', max_length=100),
        ),
    ]
