# Generated by Django 5.2.16 on 2026-07-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_estacion_hardware_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='monitorear_recursos',
            field=models.BooleanField(default=False, help_text='Si está activo, el agente de esta estación reporta métricas de RAM/CPU/latencia.'),
        ),
    ]
