# Generated by Django 5.2.16 on 2026-07-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_estacion_monitorear_recursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='es_cache_farmacia',
            field=models.BooleanField(default=False, help_text='Si está activo, el agente sirve los paquetes de despliegue por LAN a su farmacia.'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='ip_lan',
            field=models.GenericIPAddressField(blank=True, help_text='IP LAN reportada por el agente.', null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='puerto_cache',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
