# Generated by Django 5.2.16 on 2026-07-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_estacion_es_cache_farmacia_estacion_ip_lan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='hostname',
            field=models.CharField(blank=True, help_text='Nombre de equipo Windows (Environment.MachineName), reportado por el agente. Puede diferir del código de estación si este se asignó manualmente.', max_length=100),
        ),
    ]
