# Generated by Django 5.2.16 on 2026-07-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_estacion_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='almacenamiento_total_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='info_equipo_fecha',
            field=models.DateTimeField(blank=True, help_text='Cuándo se actualizó por última vez la info de hardware.', null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='procesador',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='estacion',
            name='ram_total_mb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
