# Generated by Django 5.2.16 on 2026-07-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_estacion_almacenamiento_total_gb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'ordering': ['codigo'], 'permissions': [('acceso_remoto_estacion', 'Puede abrir sesiones de acceso remoto (MeshCentral) a estaciones')]},
        ),
        migrations.AddField(
            model_name='estacion',
            name='meshcentral_node_id',
            field=models.CharField(blank=True, help_text='ID interno del dispositivo en MeshCentral (se copia manualmente desde la consola de MeshCentral tras instalar el agente). Vacío = no vinculada.', max_length=64),
        ),
        migrations.AddField(
            model_name='estacion',
            name='meshcentral_vinculado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
