# Generated by Django 5.2.16 on 2026-07-29 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def crear_unidades_negocio(apps, schema_editor):
    """Siembra las dos unidades de negocio reales de la empresa (SG/MIA).

    A diferencia de la asignación Farmacia->UnidadNegocio (que requiere criterio
    humano y queda pendiente como tarea manual), las unidades en sí son datos fijos
    conocidos de antemano, así que se crean automáticamente al migrar.
    """
    UnidadNegocio = apps.get_model('catalogo', 'UnidadNegocio')
    UnidadNegocio.objects.get_or_create(codigo='SG', defaults={'nombre': 'Farmacias San Gregorio'})
    UnidadNegocio.objects.get_or_create(codigo='MIA', defaults={'nombre': 'Farmacias MIA'})


def eliminar_unidades_negocio(apps, schema_editor):
    UnidadNegocio = apps.get_model('catalogo', 'UnidadNegocio')
    UnidadNegocio.objects.filter(codigo__in=['SG', 'MIA']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_estacion_options_estacion_meshcentral_node_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El código de unidad de negocio solo admite mayúsculas y números, ej. SG', regex='^[A-Z0-9]+$')])),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidad de negocio',
                'verbose_name_plural': 'Unidades de negocio',
                'db_table': 'unidad_negocio',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='farmacia',
            name='fecha_apertura',
            field=models.DateField(blank=True, help_text='Fecha real de apertura del local (distinta de fecha_registro, que es cuándo se creó el registro en SAIDSOFT).', null=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='unidad_negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmacias', to='catalogo.unidadnegocio'),
        ),
        migrations.RunPython(crear_unidades_negocio, eliminar_unidades_negocio),
    ]
