# Generated by Django 5.2.16 on 2026-08-03 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_farmacia_unidad_negocio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'ordering': ['codigo'], 'permissions': [('acceso_remoto_estacion', 'Puede abrir sesiones de acceso remoto (MeshCentral) a estaciones'), ('supervision_auditoria_estacion', 'Puede ver grabaciones de sesión (auditoría) de estaciones')]},
        ),
    ]
