# Generated by Django 5.2.16 on 2026-08-03 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_alter_estacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'ordering': ['codigo'], 'permissions': [('acceso_remoto_estacion', 'Puede abrir sesiones de acceso remoto (MeshCentral) a estaciones'), ('supervision_auditoria_estacion', 'Puede ver grabaciones de sesión (auditoría) de estaciones'), ('ver_clave_bitlocker', 'Puede ver la clave de recuperación de BitLocker de estaciones')]},
        ),
        migrations.AddField(
            model_name='estacion',
            name='bitlocker_habilitado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='bitlocker_metodo_proteccion',
            field=models.CharField(blank=True, help_text='Ej. tpm, tpm_pin, password — tal como lo reporta el agente (Get-BitLockerVolume). Texto libre, no choices: los protectores de BitLocker no son un set fijo pequeño.', max_length=30),
        ),
        migrations.CreateModel(
            name='ClaveRecuperacionBitLocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_cifrada', models.TextField(help_text='Token Fernet — nunca texto plano.')),
                ('id_protector', models.CharField(blank=True, help_text='Recovery Key ID de BitLocker (no sensible por sí solo): ayuda a confirmar en Windows que es la clave correcta antes de aplicarla.', max_length=100)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('estacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clave_bitlocker', to='catalogo.estacion')),
            ],
            options={
                'verbose_name': 'Clave de recuperación BitLocker',
                'verbose_name_plural': 'Claves de recuperación BitLocker',
                'db_table': 'clave_recuperacion_bitlocker',
            },
        ),
    ]
