# Generated by Django 5.2.16 on 2026-08-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_alter_estacion_options_estacion_bitlocker_habilitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='segmento_red',
            field=models.CharField(blank=True, help_text='Subred asignada al enlace de la farmacia (ej. 10.110.1.96/27), del inventario de red del proveedor — sirve para diagnosticar conectividad sin volver al Excel original.', max_length=30),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='tiene_backup',
            field=models.BooleanField(default=False, help_text='Si el sitio tiene enlace de respaldo — sin uno, una caída del enlace principal deja a la farmacia sin conectividad (punto único de falla).'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='tipo_enlace',
            field=models.CharField(blank=True, help_text='Proveedor/tecnología del enlace principal (ej. TELCONET, PUNTO NET).', max_length=30),
        ),
    ]
