# Generated by Django 5.2.16 on 2026-08-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_farmacia_segmento_red_farmacia_tiene_backup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='windows_update_detalle',
            field=models.JSONField(blank=True, default=list, help_text='Actualizaciones pendientes detectadas en el último escaneo: [{"titulo": ..., "kb": ...}, ...].'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='windows_update_pendientes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='windows_update_requiere_reinicio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='windows_update_ultima_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
