# Generated by Django 5.2.16 on 2026-08-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_estacion_windows_update_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='windows_update_ultimo_error',
            field=models.CharField(blank=True, help_text='Motivo del último escaneo fallido (ej. sin salida a internet). Vacío = el último escaneo salió bien o todavía no se escaneó. Muchas estaciones no tienen salida a internet por defecto — este campo es lo que le avisa al operador que hay que habilitársela para poder escanear esa estación puntual.', max_length=255),
        ),
    ]
