# Generated by Django 5.2.16 on 2026-08-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_estacion_windows_update_ultimo_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'ordering': ['codigo'], 'permissions': [('acceso_remoto_estacion', 'Puede abrir sesiones de acceso remoto (MeshCentral) a estaciones'), ('supervision_auditoria_estacion', 'Puede ver grabaciones de sesión (auditoría) de estaciones'), ('ver_clave_bitlocker', 'Puede ver la clave de recuperación de BitLocker de estaciones'), ('consultar_info_estacion', 'Puede pedir refresco de información (hardware/BitLocker) de una estación'), ('aprobar_estacion', 'Puede aprobar o rechazar el enrolamiento de una estación'), ('reiniciar_estacion', 'Puede reiniciar remotamente una estación'), ('escanear_actualizaciones_estacion', 'Puede disparar un escaneo de Windows Update en una estación')]},
        ),
    ]
