# Generated by Django 5.2.16 on 2026-08-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_estacion_permisos_soporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='software_instalado_ultima_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
