# Generated by Django 5.2.16 on 2026-08-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_estacion_software_instalado_ultima_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='power_plan_actual',
            field=models.CharField(blank=True, help_text='Nombre del plan de energía activo (ej. "Equilibrado", "Alto rendimiento"), tal como lo reporta Windows (Win32_PowerPlan).', max_length=100),
        ),
        migrations.AddField(
            model_name='estacion',
            name='power_plan_ultima_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
