# Generated by Django 5.2.16 on 2026-08-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_estacion_power_plan_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='ip_router',
            field=models.GenericIPAddressField(blank=True, help_text='IP del Mikrotik de la farmacia, para sondeo SNMP de ancho de banda (ver apps.monitoreo.mikrotik). Vacío = esta farmacia no se sondea, sin romper nada más.', null=True),
        ),
    ]
