# Generated by Django 5.2.16 on 2026-08-22 20:51

import apps.catalogo.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_farmacia_ip_router'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'ordering': ['codigo'], 'permissions': [('acceso_remoto_estacion', 'Puede abrir sesiones de acceso remoto (MeshCentral) a estaciones'), ('supervision_auditoria_estacion', 'Puede ver grabaciones de sesión (auditoría) de estaciones'), ('ver_clave_bitlocker', 'Puede ver la clave de recuperación de BitLocker de estaciones'), ('consultar_info_estacion', 'Puede pedir refresco de información (hardware/BitLocker) de una estación'), ('aprobar_estacion', 'Puede aprobar o rechazar el enrolamiento de una estación'), ('reiniciar_estacion', 'Puede reiniciar remotamente una estación'), ('escanear_actualizaciones_estacion', 'Puede disparar un escaneo de Windows Update en una estación'), ('actualizar_agente_estacion', 'Puede actualizar remotamente el agente de una estación')]},
        ),
        migrations.CreateModel(
            name='VersionAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30, unique=True)),
                ('ejecutable', models.FileField(upload_to=apps.catalogo.models.ruta_ejecutable_agente)),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('tamanio_bytes', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('notas', models.TextField(blank=True, help_text='Qué cambió en este build (opcional).')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones_agente_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión de agente',
                'verbose_name_plural': 'Versiones de agente',
                'db_table': 'version_agente',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
