# Generated by Django 5.2.16 on 2026-08-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0019_colaborador_usuario'),
        ('catalogo', '0019_alter_estacion_options_versionagente'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='administrador',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='coordinador_regional',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='coordinador_zonal',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='extension_telefonica',
            field=models.PositiveIntegerField(blank=True, help_text='Extensión interna (PBX), no una IP pese al nombre de la columna original.', null=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='fecha_inicio_operacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='fecha_inicio_ruc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='formato_farmacia',
            field=models.CharField(blank=True, choices=[('mostrador', 'Mostrador'), ('mostrador_xp', 'Mostrador XP'), ('autoservicio', 'Autoservicio'), ('categorias', 'Categorías')], max_length=20),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='horario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='parroquia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, help_text='Técnico de soporte responsable de esta sucursal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmacias_asignadas', to='activos.colaborador'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='tipo_sucursal',
            field=models.CharField(blank=True, choices=[('propia', 'Propia'), ('asociado', 'Asociado')], max_length=15),
        ),
    ]
