# Generated by Django 5.2.16 on 2026-08-24 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_farmacia_administrador_farmacia_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='perifericos_ultima_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PerifericoDetectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fabricante', models.CharField(blank=True, max_length=150)),
                ('clase', models.CharField(blank=True, help_text='PNPClass de Windows: Keyboard, Mouse, Printer, HIDClass, USB, DiskDrive, Image, etc.', max_length=100)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('detectado_en', models.DateTimeField(auto_now_add=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perifericos_detectados', to='catalogo.estacion')),
            ],
            options={
                'verbose_name': 'Periférico detectado',
                'verbose_name_plural': 'Periféricos detectados',
                'db_table': 'periferico_detectado',
                'ordering': ['estacion', 'nombre'],
                'unique_together': {('estacion', 'device_id')},
            },
        ),
    ]
