# Generated by Django 5.2.16 on 2026-08-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0021_estacion_perifericos_ultima_verificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='pos_bdd',
            field=models.CharField(blank=True, help_text='Base de datos del POS, ej. trx004.', max_length=50),
        ),
        migrations.AddField(
            model_name='estacion',
            name='pos_puerto',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='estacion',
            name='pos_servidor',
            field=models.CharField(blank=True, help_text='IP/host del servidor del POS.', max_length=100),
        ),
    ]
