# Generated by Django 5.2.16 on 2026-08-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0022_estacion_pos_bdd_estacion_pos_puerto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='pos_puerto',
            field=models.CharField(blank=True, help_text='Puerto del servidor, ej. 5433.', max_length=10),
        ),
        migrations.AddField(
            model_name='grupo',
            name='pos_servidor',
            field=models.CharField(blank=True, help_text='IP/host del servidor de base de datos de este nodo, ej. 192.168.112.3.', max_length=100),
        ),
    ]
