# Generated by Django 5.2.16 on 2026-08-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0023_grupo_pos_puerto_grupo_pos_servidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='pos_password_cifrada',
            field=models.TextField(blank=True, help_text='Token Fernet — nunca texto plano. Contraseña de la BD de este nodo.'),
        ),
    ]
