# Generated by Django 5.2.16 on 2026-08-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0024_grupo_pos_password_cifrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='pos_bdd',
            field=models.CharField(blank=True, help_text='Nombre exacto de la base en el .Config (sensible a mayúsculas). Vacío = el código en minúscula.', max_length=50),
        ),
    ]
