# Generated by Django 5.2.16 on 2026-09-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0025_grupo_pos_bdd'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='circuito_proveedor',
            field=models.CharField(blank=True, help_text='Nombre del circuito en el proveedor (ej. "sangregorio2-santana"). Es el identificador que pide TELCONET/PUNTO NET al abrir un ticket: sin él hay que buscarlo en una planilla aparte mientras la farmacia está sin vender.', max_length=80),
        ),
    ]
