# Generated by Django 5.2.16 on 2026-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0026_farmacia_circuito_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='desfase_reloj_segundos',
            field=models.IntegerField(blank=True, help_text='Diferencia entre el reloj de la estación y el del servidor, en segundos (positivo = la estación va adelantada). Incluye la latencia del camino MQTT, así que no es una medida de precisión NTP: sirve para detectar desfases de segundos o minutos, no de milisegundos.', null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='offset_utc_minutos',
            field=models.SmallIntegerField(blank=True, help_text='Offset UTC de la zona horaria configurada, en minutos. Ecuador es -300 (UTC-5, sin horario de verano); cualquier otro valor es una región mal asignada.', null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='zona_horaria',
            field=models.CharField(blank=True, help_text='Identificador de zona horaria de Windows tal como lo reporta `tzutil /g`, ej. "SA Pacific Standard Time".', max_length=60),
        ),
    ]
