# Generated by Django 5.2.16 on 2026-09-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0027_estacion_desfase_reloj_segundos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='ancho_contratado_mbps',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Megabits por segundo contratados al proveedor. Vacío = no se sabe, que NO es lo mismo que cero ni que el valor típico: sin este dato el consumo se puede mostrar, pero no se puede decir si es mucho o poco.', null=True, verbose_name='Ancho contratado (Mbps)'),
        ),
    ]
