# Generated by Django 5.2.16 on 2026-09-16 13:37

import secrets

from django.db import migrations, models


def sembrar_secretos(apps, schema_editor):
    """Un secreto distinto por estación ya existente.

    No se puede hacer con un UPDATE masivo: el objetivo es justamente que cada estación
    tenga el suyo, así que un valor calculado una vez y aplicado a todas sería el mismo
    secreto compartido que esto viene a reemplazar.
    """
    Estacion = apps.get_model('catalogo', 'Estacion')
    for estacion in Estacion.objects.filter(hmac_secret='').only('pk'):
        estacion.hmac_secret = secrets.token_hex(32)
        estacion.save(update_fields=['hmac_secret'])


def borrar_secretos(apps, schema_editor):
    apps.get_model('catalogo', 'Estacion').objects.update(hmac_secret='')


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0028_farmacia_ancho_contratado_mbps'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='hmac_secret',
            field=models.CharField(blank=True, editable=False, help_text='Secreto con el que se firman los comandos dirigidos SOLO a esta estación. Se entrega en la respuesta de enrolamiento, por el mismo canal que la credencial MQTT propia. Reemplaza al COMANDO_HMAC_SECRET compartido de la flota, que hoy hay que escribir a mano en el config.txt de cada equipo y que, filtrado, permite fabricar un ejecutar_script válido para cualquiera de las 700 farmacias (§10-Z).', max_length=64),
        ),
        migrations.RunPython(sembrar_secretos, borrar_secretos),
    ]
