# Generated by Django 5.2.16 on 2026-09-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0029_hmac_por_estacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='hmac_propio_confirmado',
            field=models.BooleanField(default=False, editable=False, help_text='La estación confirmó en su heartbeat que tiene guardado su secreto propio. Es lo único que habilita a firmarle con él.'),
        ),
    ]
