"""Freno de emergencia: pausar y reanudar el agente de una estacion a distancia.

Hasta ahora lo unico para frenar un agente era mandarle `Stop-Service` por
`ejecutar_script`, y eso tiene tres problemas que lo vuelven inservible como freno de
una flota: no llega a una estacion apagada (`/comando/` es fire-and-forget), exige que
el agente que queres frenar todavia funcione, y es de IDA SOLA — sin agente no queda
canal para volver a arrancarlo.

Una estacion pausada SIGUE LATIENDO. Es deliberado: callarla del todo la haria aparecer
caida en el panel y perderias visibilidad justo durante la emergencia.

`pausa_solicitada_en` y `pausa_confirmada_en` estan separadas a proposito. La orden va
retenida, asi que publicarla no prueba que se haya aplicado: hasta que la estacion lo
confirme en su latido, lo unico cierto es que el mensaje salio. Confundir las dos cosas
es creer que frenaste 1.800 equipos cuando frenaste los que estaban encendidos.
"""
# Generated by Django 5.2.16 on 2026-09-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0030_hmac_propio_confirmado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'ordering': ['codigo'], 'permissions': [('acceso_remoto_estacion', 'Puede abrir sesiones de acceso remoto (MeshCentral) a estaciones'), ('supervision_auditoria_estacion', 'Puede ver grabaciones de sesión (auditoría) de estaciones'), ('ver_clave_bitlocker', 'Puede ver la clave de recuperación de BitLocker de estaciones'), ('consultar_info_estacion', 'Puede pedir refresco de información (hardware/BitLocker) de una estación'), ('aprobar_estacion', 'Puede aprobar o rechazar el enrolamiento de una estación'), ('reiniciar_estacion', 'Puede reiniciar remotamente una estación'), ('escanear_actualizaciones_estacion', 'Puede disparar un escaneo de Windows Update en una estación'), ('actualizar_agente_estacion', 'Puede actualizar remotamente el agente de una estación'), ('pausar_estacion', 'Puede pausar y reanudar remotamente el agente de estaciones')]},
        ),
        migrations.AddField(
            model_name='estacion',
            name='pausa_confirmada_en',
            field=models.DateTimeField(blank=True, editable=False, help_text='Cuándo la estación confirmó el estado en su latido. Mientras esté vacío o sea anterior a la solicitud, la orden viajó pero NADIE confirmó que se aplicó — que es la diferencia entre creer que frenaste la flota y haberla frenado.', null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='pausa_solicitada_en',
            field=models.DateTimeField(blank=True, editable=False, help_text='Cuándo se publicó la orden. La estación puede tardar en recibirla si está apagada: el mensaje va retenido y le llega al reconectarse.', null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='pausado',
            field=models.BooleanField(default=False, help_text='Freno de emergencia: la estación sigue reportando su latido pero deja de ejecutar comandos y de reportar métricas, servicios, log del POS y eventos. Reversible desde el panel; sigue aceptando actualizaciones del agente.'),
        ),
    ]
