"""El agente se corrige el reloj solo, y el servidor lleva la cuenta.

Pasados los 120 s de desfase la estacion descarta TODO mensaje firmado, incluido el
script que le arreglaria la hora: circulo vicioso que hasta ahora solo se rompia entrando
por MeshCentral a mano. El agente 0.30 detecta ese rechazo y corre `net time` contra el
ServidorHora de su config.

El contador vive aca porque arreglar el sintoma TAPA la senal: un equipo con la pila de
CMOS agotada antes se delataba quedandose sordo; ahora se corrige solo y nadie se entera.
El numero es lo unico que lo delata.
"""
# Generated by Django 5.2.16 on 2026-09-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0031_pausa_remota_de_estaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='autocorrecciones_reloj',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Veces que la estación se corrigió el reloj sola contra el servidor de hora (agente 0.30+). Que pase una vez es lo esperado: rompe el círculo vicioso de una estación que descarta todo comando, incluido el que le arreglaría la hora. Que suba seguido señala la pila de CMOS agotada — eso no se configura, se cambia el equipo.'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='ultima_autocorreccion_reloj',
            field=models.DateTimeField(blank=True, editable=False, help_text='Cuándo se corrigió el reloj por última vez, según la propia estación.', null=True),
        ),
    ]
