# Generated by Django 5.2.16 on 2026-09-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0033_baja_de_integraciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='tipo',
            field=models.CharField(choices=[('farmacia', 'Farmacia'), ('tienda', 'Tienda'), ('administrativo', 'Sitio administrativo')], default='farmacia', help_text='Qué es este sitio. Default `farmacia` para no cambiarle el comportamiento a nada de lo que ya existe. Lo propio de una farmacia (sondeo de enlace, alertas del POS, SNMP) NO depende de este campo: se activa por datos (ip_router, servicios reportados), así que un sitio administrativo sin esos datos simplemente no los dispara.', max_length=20),
        ),
    ]
