# Generated by Django 5.2.16 on 2026-09-11 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0026_farmacia_circuito_proveedor'),
        ('despliegues', '0006_alter_despliegue_options'),
        ('scripts', '0005_alter_ejecucionscript_options_and_more'),
        ('software', '0005_aplicacioncatalogo_version_mas_reciente_conocida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantilla_version', models.PositiveIntegerField(help_text='Versión de la plantilla con la que se generó esta apertura. Copiada al crear: editar la plantilla después no reescribe lo que esta apertura ejecutó.')),
                ('fecha_prevista', models.DateField(help_text='Fecha prevista de apertura del local.')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobada', 'Aprobada (esperando equipos)'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='borrador', max_length=25)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_creadas', to=settings.AUTH_USER_MODEL)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas', to='catalogo.farmacia')),
            ],
            options={
                'db_table': 'apertura',
                'ordering': ['-fecha_prevista', '-fecha_creacion'],
                'permissions': [('aprobar_apertura', 'Puede aprobar una apertura pendiente de aprobación'), ('emitir_token_apertura', 'Puede emitir y ver los tokens de enrolamiento de una apertura')],
            },
        ),
        migrations.CreateModel(
            name='PasoApertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('script', 'Ejecutar script'), ('software', 'Instalar software del catálogo'), ('despliegue_pos', 'Instalar el POS (despliegue ya aprobado)'), ('verificacion', 'Verificar estado reportado'), ('activo_itam', 'Dar de alta en el inventario (ITAM)'), ('manual', 'Paso manual (fuera de SAIDSOFT)')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('error', 'Error'), ('omitido', 'Omitido')], default='pendiente', max_length=15)),
                ('detalle', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('apertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='aperturas.apertura')),
                ('ejecucion_script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_apertura', to='scripts.ejecucionscript')),
                ('estacion', models.ForeignKey(blank=True, help_text='Vacío en los pasos manuales, que son de la farmacia y no de un equipo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasos_apertura', to='catalogo.estacion')),
                ('solicitud_instalacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_apertura', to='software.solicitudinstalacion')),
            ],
            options={
                'verbose_name': 'Paso de apertura',
                'verbose_name_plural': 'Pasos de apertura',
                'db_table': 'paso_apertura',
                'ordering': ['apertura', 'estacion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='EventoApertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('creado', 'Paso creado'), ('enrolada', 'Estación enrolada por token de apertura'), ('enviado', 'Trabajo enviado a la estación'), ('completado', 'Completado'), ('error', 'Error'), ('omitido', 'Omitido')], max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='aperturas.pasoapertura')),
            ],
            options={
                'verbose_name': 'Evento de apertura',
                'verbose_name_plural': 'Eventos de apertura',
                'db_table': 'evento_apertura',
                'ordering': ['paso', 'timestamp', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PasoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('script', 'Ejecutar script'), ('software', 'Instalar software del catálogo'), ('despliegue_pos', 'Instalar el POS (despliegue ya aprobado)'), ('verificacion', 'Verificar estado reportado'), ('activo_itam', 'Dar de alta en el inventario (ITAM)'), ('manual', 'Paso manual (fuera de SAIDSOFT)')], max_length=20)),
                ('verificacion', models.CharField(blank=True, choices=[('bitlocker', 'Disco cifrado con BitLocker'), ('software_presente', 'Software presente en el inventario'), ('windows_update_escaneado', 'Windows Update escaneado al menos una vez'), ('version_pos_objetivo', 'POS en la versión objetivo de su grupo'), ('nodo_pos_coherente', 'El nodo del POS coincide con el grupo')], help_text='Requerido si el tipo es "Verificar estado reportado".', max_length=30)),
                ('parametro', models.CharField(blank=True, help_text='Dato suelto del paso. Para la verificación "software presente", el nombre (o parte) del programa que se busca en el inventario, ej. "ESET".', max_length=150)),
                ('rol_estacion', models.CharField(blank=True, choices=[('caja', 'Caja'), ('administracion', 'Administración'), ('servidor', 'Servidor de farmacia')], help_text='Vacío = el paso corre en TODAS las estaciones de la apertura. Con valor, solo en las de ese rol. Los pasos manuales son de la farmacia, no de una estación, y este campo se ignora.', max_length=20)),
                ('obligatorio', models.BooleanField(default=True, help_text='Un paso no obligatorio que falla no impide completar la apertura.')),
                ('timeout_segundos', models.PositiveIntegerField(default=300)),
                ('despliegue', models.ForeignKey(blank=True, help_text='Requerido si el tipo es "Instalar el POS". Debe ser un despliegue ya aprobado: la apertura no crea paquetes nuevos ni saltea la aprobación de un despliegue, solo suma la estación recién enrolada a uno que ya pasó por su propio control de cuatro ojos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pasos_apertura', to='despliegues.despliegue')),
                ('script', models.ForeignKey(blank=True, help_text='Requerido si el tipo es "Ejecutar script".', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pasos_apertura', to='scripts.script')),
                ('version_aplicacion', models.ForeignKey(blank=True, help_text='Requerido si el tipo es "Instalar software del catálogo".', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pasos_apertura', to='software.versionaplicacion')),
            ],
            options={
                'verbose_name': 'Paso de plantilla',
                'verbose_name_plural': 'Pasos de plantilla',
                'db_table': 'paso_plantilla_apertura',
                'ordering': ['plantilla', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='pasoapertura',
            name='paso_plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='aperturas.pasoplantilla'),
        ),
        migrations.CreateModel(
            name='PlantillaApertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('formato_farmacia', models.CharField(blank=True, choices=[('mostrador', 'Mostrador'), ('mostrador_xp', 'Mostrador XP'), ('autoservicio', 'Autoservicio'), ('categorias', 'Categorías')], help_text='Vacío = aplica a cualquier formato. Un autoservicio y un mostrador no tienen la misma cantidad de cajas, y de ahí salen los perfiles de estación.', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_apertura_creadas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, help_text='Vacío = aplica a cualquier canal de la unidad de negocio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_apertura', to='catalogo.grupo')),
                ('unidad_negocio', models.ForeignKey(help_text='Cliente dueño de la plantilla. Una apertura solo puede usar plantillas de la unidad de negocio de su propia farmacia.', on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_apertura', to='catalogo.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Plantilla de apertura',
                'verbose_name_plural': 'Plantillas de apertura',
                'db_table': 'plantilla_apertura',
                'ordering': ['nombre', '-version'],
                'unique_together': {('unidad_negocio', 'nombre', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PerfilEstacionPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sufijo', models.CharField(help_text='Sufijo del código de estación, sin la farmacia ni el guion (ej. "ADM", "A", "B").', max_length=10)),
                ('rol', models.CharField(choices=[('caja', 'Caja'), ('administracion', 'Administración'), ('servidor', 'Servidor de farmacia')], default='caja', max_length=20)),
                ('obligatoria', models.BooleanField(default=True, help_text='Si está marcada, la apertura no se da por completada hasta que esta estación se haya enrolado y terminado sus pasos.')),
                ('monitorear_recursos', models.BooleanField(default=False, help_text='Se aplica a la estación al enrolarse (típicamente solo el servidor).')),
                ('es_cache_farmacia', models.BooleanField(default=False, help_text='Se aplica a la estación al enrolarse. Una sola por farmacia: sirve los paquetes por LAN al resto de las cajas.')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_estacion', to='aperturas.plantillaapertura')),
            ],
            options={
                'verbose_name': 'Perfil de estación',
                'verbose_name_plural': 'Perfiles de estación',
                'db_table': 'perfil_estacion_plantilla',
                'ordering': ['plantilla', 'sufijo'],
                'unique_together': {('plantilla', 'sufijo')},
            },
        ),
        migrations.AddField(
            model_name='pasoplantilla',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='aperturas.plantillaapertura'),
        ),
        migrations.AddField(
            model_name='apertura',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas', to='aperturas.plantillaapertura'),
        ),
        migrations.CreateModel(
            name='TokenApertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('prefijo', models.CharField(editable=False, help_text='Primeros caracteres del token, para poder identificarlo en el panel sin revelarlo.', max_length=8)),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('hardware_id', models.CharField(blank=True, help_text='hardware_id del equipo que consumió el token.', max_length=100)),
                ('revocado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('apertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='aperturas.apertura')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens_apertura_emitidos', to=settings.AUTH_USER_MODEL)),
                ('estacion', models.ForeignKey(blank=True, help_text='La estación que consumió este token.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_apertura', to='catalogo.estacion')),
                ('perfil', models.ForeignKey(help_text='Qué estación de la plantilla se espera que use este token.', on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='aperturas.perfilestacionplantilla')),
            ],
            options={
                'verbose_name': 'Token de apertura',
                'verbose_name_plural': 'Tokens de apertura',
                'db_table': 'token_apertura',
                'ordering': ['apertura', 'perfil__sufijo'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='pasoapertura',
            unique_together={('apertura', 'paso_plantilla', 'estacion')},
        ),
        migrations.AlterUniqueTogether(
            name='pasoplantilla',
            unique_together={('plantilla', 'orden')},
        ),
        migrations.AddConstraint(
            model_name='apertura',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['borrador', 'pendiente_aprobacion', 'aprobada', 'en_curso'])), fields=('farmacia',), name='una_apertura_vigente_por_farmacia'),
        ),
    ]
