# Generated by Django 5.2.16 on 2026-08-03 05:23

import apps.software.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0011_alter_estacion_options_estacion_bitlocker_habilitado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fabricante', models.CharField(blank=True, max_length=150)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('comando_deteccion', models.TextField(blank=True, help_text='PowerShell opcional que el agente corre antes de instalar, para saber si ya está presente y qué versión tiene — evita reinstalar innecesariamente. Sin implementar todavía del lado del agente (ver README).')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_catalogo_creadas', to=settings.AUTH_USER_MODEL)),
                ('unidad_negocio', models.ForeignKey(blank=True, help_text='Vacío = aplicación compartida, visible e instalable por cualquier cliente. Con valor = privada de esa unidad de negocio (mismo criterio que Script).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_catalogo', to='catalogo.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Aplicación de catálogo',
                'verbose_name_plural': 'Aplicaciones de catálogo',
                'db_table': 'aplicacion_catalogo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('descargando', 'Descargando'), ('descargado', 'Descargado'), ('verificado', 'Hash verificado'), ('instalando', 'Instalando'), ('instalado', 'Instalado'), ('error', 'Error')], default='pendiente', max_length=15)),
                ('version_previa_detectada', models.CharField(blank=True, max_length=50)),
                ('version_instalada', models.CharField(blank=True, max_length=50)),
                ('detalle_error', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_instalacion', to='catalogo.estacion')),
            ],
            options={
                'db_table': 'resultado_instalacion',
                'ordering': ['solicitud', 'estacion'],
            },
        ),
        migrations.CreateModel(
            name='EventoInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.CharField(choices=[('publicado', 'Publicado por el panel'), ('recibido', 'Recibido por el agente'), ('descargado', 'Descargado'), ('hash_verificado', 'Hash verificado'), ('instalando', 'Instalando'), ('instalado', 'Instalado'), ('error', 'Error')], max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='software.resultadoinstalacion')),
            ],
            options={
                'verbose_name': 'Evento de instalación',
                'verbose_name_plural': 'Eventos de instalación',
                'db_table': 'evento_instalacion',
                'ordering': ['resultado', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('instalar', 'Instalar'), ('actualizar', 'Actualizar'), ('desinstalar', 'Desinstalar')], default='instalar', max_length=15)),
                ('destino_tipo', models.CharField(choices=[('cadena', 'Toda la cadena'), ('grupos', 'Grupos específicos'), ('farmacias', 'Farmacias específicas'), ('estaciones', 'Estaciones específicas')], max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicando', 'Publicando'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_instalacion_creadas', to=settings.AUTH_USER_MODEL)),
                ('estaciones', models.ManyToManyField(blank=True, related_name='solicitudes_instalacion', to='catalogo.estacion')),
                ('farmacias', models.ManyToManyField(blank=True, related_name='solicitudes_instalacion', to='catalogo.farmacia')),
                ('grupos', models.ManyToManyField(blank=True, related_name='solicitudes_instalacion', to='catalogo.grupo')),
                ('unidad_negocio', models.ForeignKey(help_text='Cliente al que se dirige. "Toda la cadena" significa toda la cadena de esta unidad de negocio, nunca de otras.', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_instalacion', to='catalogo.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Solicitud de instalación',
                'verbose_name_plural': 'Solicitudes de instalación',
                'db_table': 'solicitud_instalacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='resultadoinstalacion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='software.solicitudinstalacion'),
        ),
        migrations.CreateModel(
            name='VersionAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('instalador', models.FileField(upload_to=apps.software.models.ruta_instalador)),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('tamanio_bytes', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('comando_instalacion_silenciosa', models.TextField(help_text='Ej. msiexec /i "{archivo}" /qn /norestart. "{archivo}" se reemplaza por la ruta local donde el agente guardó el instalador descargado.')),
                ('comando_desinstalacion', models.TextField(blank=True)),
                ('argumentos_adicionales', models.CharField(blank=True, max_length=500)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='software.aplicacioncatalogo')),
            ],
            options={
                'verbose_name': 'Versión de aplicación',
                'verbose_name_plural': 'Versiones de aplicación',
                'db_table': 'version_aplicacion',
                'ordering': ['-fecha_publicacion'],
                'unique_together': {('aplicacion', 'version')},
            },
        ),
        migrations.AddField(
            model_name='solicitudinstalacion',
            name='version_aplicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='software.versionaplicacion'),
        ),
        migrations.AlterUniqueTogether(
            name='resultadoinstalacion',
            unique_together={('solicitud', 'estacion')},
        ),
    ]
