# Generated by Django 5.2.16 on 2026-08-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventoinstalacion',
            options={'ordering': ['resultado', 'timestamp', 'pk'], 'verbose_name': 'Evento de instalación', 'verbose_name_plural': 'Eventos de instalación'},
        ),
    ]
