# Generated by Django 5.2.16 on 2026-08-17 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_estacion_software_instalado_ultima_verificacion'),
        ('software', '0002_alter_eventoinstalacion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareInstaladoDetectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('fabricante', models.CharField(blank=True, max_length=150)),
                ('detectado_en', models.DateTimeField(auto_now_add=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_instalado', to='catalogo.estacion')),
            ],
            options={
                'verbose_name': 'Software instalado detectado',
                'verbose_name_plural': 'Software instalado detectado',
                'db_table': 'software_instalado_detectado',
                'ordering': ['estacion', 'nombre'],
                'unique_together': {('estacion', 'nombre')},
            },
        ),
    ]
