# Generated by Django 5.2.16 on 2026-08-17 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_estacion_power_plan_actual_and_more'),
        ('software', '0003_softwareinstaladodetectado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino_tipo', models.CharField(choices=[('cadena', 'Toda la cadena'), ('grupos', 'Grupos específicos'), ('farmacias', 'Farmacias específicas'), ('estaciones', 'Estaciones específicas')], max_length=20)),
                ('frecuencia_dias', models.PositiveIntegerField()),
                ('fecha_ultima_ejecucion', models.DateField(blank=True, null=True)),
                ('fecha_proxima_ejecucion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_programados_creados', to=settings.AUTH_USER_MODEL)),
                ('estaciones', models.ManyToManyField(blank=True, related_name='inventarios_programados', to='catalogo.estacion')),
                ('farmacias', models.ManyToManyField(blank=True, related_name='inventarios_programados', to='catalogo.farmacia')),
                ('grupos', models.ManyToManyField(blank=True, related_name='inventarios_programados', to='catalogo.grupo')),
                ('unidad_negocio', models.ForeignKey(help_text='Cliente al que se dirige. "Toda la cadena" significa toda la cadena de esta unidad de negocio, nunca de otras.', on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_programados', to='catalogo.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Inventario de software programado',
                'verbose_name_plural': 'Inventarios de software programados',
                'db_table': 'inventario_programado',
                'ordering': ['fecha_proxima_ejecucion'],
            },
        ),
    ]
