# Generated by Django 5.2.16 on 2026-08-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_inventarioprogramado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacioncatalogo',
            name='version_mas_reciente_conocida',
            field=models.CharField(blank=True, help_text='Última versión conocida de esta aplicación, cargada a mano — se compara contra el inventario de software detectado (R7) para avisar qué estaciones quedaron atrás. Vacío = esta aplicación no se vigila por versión.', max_length=50),
        ),
    ]
