"""Borrar una estación deja de llevarse el acta de sus instalaciones.

`ResultadoInstalacion.estacion` pasa de CASCADE a PROTECT, por el mismo motivo y en la
misma tanda que `ResultadoDespliegue` (ver despliegues/0007): esa fila y su
`EventoInstalacion` son la evidencia de que una aplicación se instaló en esa caja.

`ResultadoInstalacion.solicitud` sigue en CASCADE: ahí el agregado es la solicitud.
"""
# Generated by Django 5.2.16 on 2026-10-07 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0035_corp_admin_y_tipo_tienda'),
        ('software', '0005_aplicacioncatalogo_version_mas_reciente_conocida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoinstalacion',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_instalacion', to='catalogo.estacion'),
        ),
    ]
