# Generated by Django 5.2.16 on 2026-09-04 03:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0021_alter_activo_codigo_sap'),
        ('catalogo', '0025_grupo_pos_bdd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_cobertura', models.CharField(help_text='Nombre de la zona (ej. "Machala Norte"). Descriptivo: lo que se valida son las farmacias asignadas.', max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zona_asignada', to='activos.colaborador')),
                ('farmacias_asignadas', models.ManyToManyField(blank=True, help_text='Puntos que le corresponden. Vacío = no se puede validar la zona y todo reporte suyo queda sin ese control.', related_name='colaboradores_asignados', to='catalogo.farmacia')),
            ],
            options={
                'verbose_name': 'Zona de colaborador',
                'verbose_name_plural': 'Zonas de colaboradores',
                'db_table': 'colaborador_zona',
                'ordering': ['colaborador__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReporteViatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Día en que se incurrió el gasto, no cuándo se cargó.')),
                ('rubro', models.CharField(choices=[('hospedaje', 'Hospedaje'), ('alimentacion', 'Alimentación'), ('movilizacion', 'Movilización')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('origen', models.CharField(blank=True, help_text='Solo para movilización.', max_length=120)),
                ('destino', models.CharField(blank=True, help_text='Solo para movilización.', max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('observado', 'Observado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=12)),
                ('factura_adjunta', models.FileField(blank=True, upload_to='viaticos/facturas/%Y/%m/')),
                ('total_factura', models.DecimalField(blank=True, decimal_places=2, help_text='Total impreso en la factura adjunta, tipeado por quien reporta. El sistema no lee el archivo: sin este dato no hay contra qué comparar el monto.', max_digits=10, null=True)),
                ('comentario_coordinador', models.TextField(blank=True, help_text='Justificación al aprobar con alertas, o qué corregir al observar.')),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_viatico', to='activos.colaborador')),
                ('farmacia_visitada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_viatico', to='catalogo.farmacia')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaticos_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de viático',
                'verbose_name_plural': 'Reportes de viáticos',
                'db_table': 'reporte_viatico',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='AlertaViatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('fuera_de_zona', 'Fuera de zona'), ('excede_tope', 'Excede el tope'), ('sin_origen_destino', 'Sin origen/destino'), ('monto_repetido', 'Monto repetido en el mes'), ('sin_planificacion', 'Sin visita planificada')], max_length=20)),
                ('detalle', models.TextField(help_text='Por qué saltó, con los números concretos.')),
                ('resuelta', models.BooleanField(default=False, help_text='Se marca sola cuando una revalidación ya no encuentra el problema.')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='viaticos.reporteviatico')),
            ],
            options={
                'verbose_name': 'Alerta de viático',
                'verbose_name_plural': 'Alertas de viáticos',
                'db_table': 'alerta_viatico',
                'ordering': ['tipo_alerta'],
            },
        ),
        migrations.AddIndex(
            model_name='reporteviatico',
            index=models.Index(fields=['colaborador', 'fecha'], name='viatico_colab_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='reporteviatico',
            index=models.Index(fields=['estado'], name='viatico_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertaviatico',
            constraint=models.UniqueConstraint(fields=('reporte', 'tipo_alerta'), name='alerta_viatico_unica_por_tipo'),
        ),
    ]
