# Generated by Django 5.2.16 on 2026-07-27 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0006_estacion_almacenamiento_total_gb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('powershell', 'PowerShell')], default='powershell', max_length=15)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('es_adhoc', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scripts_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'script',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_snapshot', models.TextField(help_text='Copia del contenido del script al momento de ejecutar; no cambia si el script se edita después.')),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('destino_tipo', models.CharField(choices=[('cadena', 'Toda la cadena'), ('grupos', 'Grupos específicos'), ('farmacias', 'Farmacias específicas'), ('estaciones', 'Estaciones específicas')], max_length=20)),
                ('timeout_segundos', models.PositiveIntegerField(default=300)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('con_errores', 'Completado con errores')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones_script_creadas', to=settings.AUTH_USER_MODEL)),
                ('estaciones', models.ManyToManyField(blank=True, related_name='ejecuciones_script', to='catalogo.estacion')),
                ('farmacias', models.ManyToManyField(blank=True, related_name='ejecuciones_script', to='catalogo.farmacia')),
                ('grupos', models.ManyToManyField(blank=True, related_name='ejecuciones_script', to='catalogo.grupo')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones', to='scripts.script')),
            ],
            options={
                'db_table': 'ejecucion_script',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEjecucionScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('ejecutando', 'Ejecutando'), ('completado', 'Completado'), ('error', 'Error'), ('timeout', 'Tiempo agotado')], default='pendiente', max_length=15)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='scripts.ejecucionscript')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_script', to='catalogo.estacion')),
            ],
            options={
                'db_table': 'resultado_ejecucion_script',
                'ordering': ['ejecucion', 'estacion'],
                'unique_together': {('ejecucion', 'estacion')},
            },
        ),
    ]
