# Generated by Django 5.2.16 on 2026-07-30 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_farmacia_unidad_negocio'),
        ('scripts', '0002_unidad_negocio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino_tipo', models.CharField(choices=[('cadena', 'Toda la cadena'), ('grupos', 'Grupos específicos'), ('farmacias', 'Farmacias específicas'), ('estaciones', 'Estaciones específicas')], max_length=20)),
                ('frecuencia_dias', models.PositiveIntegerField()),
                ('timeout_segundos', models.PositiveIntegerField(default=300)),
                ('fecha_ultima_ejecucion', models.DateField(blank=True, null=True)),
                ('fecha_proxima_ejecucion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scripts_programados_creados', to=settings.AUTH_USER_MODEL)),
                ('estaciones', models.ManyToManyField(blank=True, related_name='scripts_programados', to='catalogo.estacion')),
                ('farmacias', models.ManyToManyField(blank=True, related_name='scripts_programados', to='catalogo.farmacia')),
                ('grupos', models.ManyToManyField(blank=True, related_name='scripts_programados', to='catalogo.grupo')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='scripts.script')),
                ('unidad_negocio', models.ForeignKey(help_text='Cliente al que se dirige. "Toda la cadena" significa toda la cadena de esta unidad de negocio, nunca de otras.', on_delete=django.db.models.deletion.PROTECT, related_name='scripts_programados', to='catalogo.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Script programado',
                'verbose_name_plural': 'Scripts programados',
                'db_table': 'script_programado',
                'ordering': ['fecha_proxima_ejecucion'],
            },
        ),
    ]
