# Generated by Django 5.2.16 on 2026-07-30 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_scriptprogramado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionscript',
            name='programado',
            field=models.ForeignKey(blank=True, help_text='Vacío = ejecución manual/ad-hoc. Con valor = generada por esta política recurrente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones_generadas', to='scripts.scriptprogramado'),
        ),
    ]
