# Generated by Django 5.2.16 on 2026-08-22 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_ejecucionscript_programado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecucionscript',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('aprobar_ejecucionscript', 'Puede aprobar una ejecución de script pendiente de aprobación')]},
        ),
        migrations.AddField(
            model_name='ejecucionscript',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones_script_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ejecucionscript',
            name='estado',
            field=models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de aprobación'), ('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('con_errores', 'Completado con errores')], default='pendiente', max_length=20),
        ),
    ]
