"""Por que una ejecucion quedo sin respuesta.

Hasta ahora una ejecucion se quedaba "En progreso" para siempre —el mas viejo llevaba 39
dias con un timeout de 300 s— y la pantalla no daba una sola pista. El dato ya existia
(desfase del reloj, pausa, ultimo latido) pero vivia en la ficha de la estacion y nadie
iba a cruzarlo a mano.
"""
# Generated by Django 5.2.16 on 2026-09-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_alter_ejecucionscript_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoejecucionscript',
            name='motivo_sin_respuesta',
            field=models.CharField(blank=True, editable=False, help_text='Por qué se dio por vencido sin respuesta, diagnosticado al cerrarlo (reloj corrido, estación pausada, apagada...). Es lo que convierte un "en progreso" eterno en algo accionable.', max_length=400),
        ),
    ]
