# Generated by Django 5.2.16 on 2026-07-27 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0011_cargo_texto_a_fk_definitivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='items_checklist', to='activos.categoriaequipo')),
            ],
            options={
                'verbose_name': 'Ítem de checklist',
                'verbose_name_plural': 'Ítems de checklist',
                'db_table': 'actividad_checklist',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_mantenimiento', models.CharField(blank=True, max_length=30)),
                ('tipo_origen', models.CharField(choices=[('odoo_helpdesk', 'Odoo Helpdesk'), ('programado', 'Programado'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('estado_interno', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('resultado_tecnico', models.CharField(blank=True, choices=[('reparado', 'Reparado'), ('sin_falla', 'Sin falla encontrada'), ('sin_intervencion', 'Sin intervención'), ('parcialmente_reparado', 'Parcialmente reparado'), ('requiere_repuesto', 'Requiere repuesto'), ('escalado_a_proveedor', 'Escalado a proveedor'), ('irreparable', 'Irreparable'), ('requiere_baja', 'Requiere baja'), ('garantia_aplicada', 'Garantía aplicada'), ('garantia_rechazada', 'Garantía rechazada'), ('actualizado', 'Actualizado'), ('instalado', 'Instalado')], max_length=25)),
                ('snapshot_equipo', models.JSONField(blank=True, default=dict, help_text='Código/serie/modelo del equipo principal, congelados al crear el mantenimiento.')),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_cerrados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, help_text='Custodio/colaborador que reporta o recibe el mantenimiento.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='activos.colaborador')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='activos.empresa')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mantenimiento',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='EventoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('programado', 'Programado'), ('iniciado', 'Iniciado'), ('checklist_actualizado', 'Checklist actualizado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], max_length=25)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='mantenimiento.mantenimiento')),
            ],
            options={
                'db_table': 'evento_mantenimiento',
                'ordering': ['mantenimiento', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_dias', models.PositiveIntegerField()),
                ('fecha_ultimo', models.DateField(blank=True, null=True)),
                ('fecha_proximo', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_programados', to='activos.activo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_programados_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento programado',
                'verbose_name_plural': 'Mantenimientos programados',
                'db_table': 'mantenimiento_programado',
                'ordering': ['fecha_proximo'],
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='mantenimiento_programado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_generados', to='mantenimiento.mantenimientoprogramado'),
        ),
        migrations.CreateModel(
            name='ActividadRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizada', models.BooleanField(default=False)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realizaciones', to='mantenimiento.actividadchecklist')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_realizadas', to='mantenimiento.mantenimiento')),
            ],
            options={
                'db_table': 'actividad_realizada',
                'ordering': ['actividad__orden'],
                'unique_together': {('mantenimiento', 'actividad')},
            },
        ),
        migrations.CreateModel(
            name='MantenimientoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='activos.activo')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='mantenimiento.mantenimiento')),
            ],
            options={
                'db_table': 'mantenimiento_equipo',
                'ordering': ['-es_principal', 'equipo__codigo'],
                'unique_together': {('mantenimiento', 'equipo')},
            },
        ),
    ]
