# Generated by Django 5.2.16 on 2026-07-27 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_cargo_texto_a_fk_definitivo'),
        ('mantenimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomantenimiento',
            name='tipo_evento',
            field=models.CharField(choices=[('programado', 'Programado'), ('iniciado', 'Iniciado'), ('checklist_actualizado', 'Checklist actualizado'), ('firmado', 'Firmado'), ('imagen_adjuntada', 'Imagen adjuntada'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], max_length=25),
        ),
        migrations.CreateModel(
            name='ActividadPlanificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_actividad', models.CharField(max_length=50)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('tiempo_estimado_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('tiempo_real_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_planificadas_creadas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_planificadas', to='activos.activo')),
                ('mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_planificadas', to='mantenimiento.mantenimiento')),
                ('mantenimiento_programado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_planificadas', to='mantenimiento.mantenimientoprogramado')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_planificadas', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(blank=True, help_text='Ubicación objetivo cuando la actividad es general, sin equipo específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_planificadas', to='activos.ubicacion')),
            ],
            options={
                'verbose_name': 'Actividad planificada',
                'verbose_name_plural': 'Actividades planificadas',
                'db_table': 'actividad_planificada',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='FirmaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_firma', models.CharField(choices=[('custodio', 'Custodio'), ('tecnico', 'Técnico')], max_length=10)),
                ('firma_base64', models.TextField()),
                ('firmado_en', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('firmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_mantenimiento', to=settings.AUTH_USER_MODEL)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='mantenimiento.mantenimiento')),
            ],
            options={
                'verbose_name': 'Firma de mantenimiento',
                'verbose_name_plural': 'Firmas de mantenimiento',
                'db_table': 'firma_mantenimiento',
                'ordering': ['-firmado_en'],
            },
        ),
        migrations.CreateModel(
            name='ImagenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='mantenimiento/imagenes/%Y/%m/')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('tamanio_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mantenimiento.mantenimiento')),
            ],
            options={
                'verbose_name': 'Imagen de mantenimiento',
                'verbose_name_plural': 'Imágenes de mantenimiento',
                'db_table': 'imagen_mantenimiento',
                'ordering': ['-subido_en'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('leida', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actividad_planificada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='mantenimiento.actividadplanificada')),
                ('mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='mantenimiento.mantenimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-creado_en'],
            },
        ),
    ]
