# Generated by Django 5.2.16 on 2026-07-27 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_alter_eventomantenimiento_tipo_evento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.BooleanField(default=True)),
                ('version_terminos', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos_monitoreo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentimiento de monitoreo',
                'verbose_name_plural': 'Consentimientos de monitoreo',
                'db_table': 'consentimiento_monitoreo',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('precision_metros', models.FloatField(blank=True, null=True)),
                ('timestamp_captura', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicación de técnico',
                'verbose_name_plural': 'Ubicaciones de técnico',
                'db_table': 'ubicacion_tecnico',
                'ordering': ['-timestamp_captura'],
            },
        ),
    ]
