# Generated by Django 5.2.16 on 2026-07-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_consentimientomonitoreo_ubicaciontecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_general',
            field=models.CharField(blank=True, choices=[('operativo', 'Operativo'), ('requiere_revision', 'Requiere revisión'), ('no_operativo', 'No operativo')], max_length=20),
        ),
    ]
