# Generated by Django 5.2.16 on 2026-08-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_mantenimiento_estado_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='informe_pdf',
            field=models.FileField(blank=True, upload_to='mantenimiento/informes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='informe_pdf_generado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventomantenimiento',
            name='tipo_evento',
            field=models.CharField(choices=[('programado', 'Programado'), ('iniciado', 'Iniciado'), ('checklist_actualizado', 'Checklist actualizado'), ('firmado', 'Firmado'), ('imagen_adjuntada', 'Imagen adjuntada'), ('informe_generado', 'Informe PDF generado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], max_length=25),
        ),
    ]
