# Generated by Django 5.2.16 on 2026-08-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_mantenimiento_informe_pdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventomantenimiento',
            options={'ordering': ['mantenimiento', 'timestamp', 'pk']},
        ),
    ]
