# Generated by Django 5.2.16 on 2026-08-05 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_alter_eventomantenimiento_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='empresa',
        ),
    ]
