# Generated by Django 5.2.16 on 2026-08-05 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0016_alter_movimientoinventario_tipo_movimiento'),
        ('mantenimiento', '0007_remove_mantenimiento_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='tiempo_real_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo real de intervención, capturado al cerrar (no siempre coincide con fecha_cierre - fecha_programada: el técnico puede pausar/retomar).', null=True),
        ),
        migrations.AlterField(
            model_name='eventomantenimiento',
            name='tipo_evento',
            field=models.CharField(choices=[('programado', 'Programado'), ('iniciado', 'Iniciado'), ('checklist_actualizado', 'Checklist actualizado'), ('firmado', 'Firmado'), ('imagen_adjuntada', 'Imagen adjuntada'), ('repuesto_registrado', 'Repuesto registrado'), ('informe_generado', 'Informe PDF generado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], max_length=25),
        ),
        migrations.CreateModel(
            name='RepuestoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repuestos_utilizados', to='activos.bodega')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_utilizados', to='mantenimiento.mantenimiento')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos_registrados', to=settings.AUTH_USER_MODEL)),
                ('tipo_consumible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_mantenimiento', to='activos.tipoconsumible')),
            ],
            options={
                'verbose_name': 'Repuesto utilizado',
                'verbose_name_plural': 'Repuestos utilizados',
                'db_table': 'repuesto_utilizado',
                'ordering': ['mantenimiento', 'registrado_en', 'pk'],
            },
        ),
    ]
