# Generated by Django 5.2.16 on 2026-08-23 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_mantenimiento_tiempo_real_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='mantenimiento_programado',
            field=models.ForeignKey(blank=True, help_text='Para avisos de "próximo a vencer" -- todavía no existe un Mantenimiento generado al momento de avisar, así que no alcanza con el FK de arriba.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='mantenimiento.mantenimientoprogramado'),
        ),
    ]
