# Generated by Django 5.2.16 on 2026-08-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0011_seed_tipos_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcuerdoNivelServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('normal', 'Normal'), ('baja', 'Baja')], max_length=10, unique=True)),
                ('horas_respuesta', models.PositiveIntegerField(help_text='Horas desde la fecha programada para INICIAR el mantenimiento.')),
                ('horas_resolucion', models.PositiveIntegerField(help_text='Horas desde la fecha programada para CERRARLO.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Acuerdo de nivel de servicio (SLA)',
                'verbose_name_plural': 'Acuerdos de nivel de servicio (SLA)',
                'db_table': 'acuerdo_nivel_servicio',
                'ordering': ['prioridad'],
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='prioridad',
            field=models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('normal', 'Normal'), ('baja', 'Baja')], default='normal', help_text='Define el SLA aplicable (ver AcuerdoNivelServicio).', max_length=10),
        ),
    ]
