# Generated by Django 5.2.16 on 2026-08-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0013_seed_acuerdos_nivel_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo_origen',
            field=models.CharField(choices=[('odoo_helpdesk', 'Odoo Helpdesk'), ('programado', 'Programado'), ('manual', 'Manual'), ('monitoreo', 'Monitoreo (automático)')], default='manual', max_length=20),
        ),
    ]
