# Generated by Django 5.2.16 on 2026-08-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0014_alter_mantenimiento_tipo_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='distancia_verificacion_metros',
            field=models.FloatField(blank=True, help_text='Distancia mínima del técnico a la farmacia durante la intervención, en metros.', null=True),
        ),
    ]
