# Generated by Django 5.2.16 on 2026-08-28 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0025_grupo_pos_bdd'),
        ('mantenimiento', '0015_mantenimiento_distancia_verificacion_metros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_planificada', models.DateField()),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_curso', 'En curso'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='planificada', max_length=12)),
                ('motivo', models.TextField(blank=True, help_text='Para qué se va: relevamiento, preventivo de ruta, etc.')),
                ('observaciones', models.TextField(blank=True, help_text='Qué se encontró, cargado al cerrar.')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('distancia_verificacion_metros', models.FloatField(blank=True, help_text='Distancia mínima del técnico a la farmacia durante la visita, en metros.', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_tecnicas_creadas', to=settings.AUTH_USER_MODEL)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas_tecnicas', to='catalogo.farmacia')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas_tecnicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita técnica',
                'verbose_name_plural': 'Visitas técnicas',
                'db_table': 'visita_tecnica',
                'ordering': ['-fecha_planificada'],
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_generados', to='mantenimiento.visitatecnica'),
        ),
    ]
