# Generated by Django 5.2.16 on 2026-09-08 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0017_seed_actividades_checklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['-fecha_programada'], 'permissions': [('asignar_tecnico', 'Puede asignar trabajo a un técnico distinto de sí mismo')]},
        ),
    ]
