# Generated by Django 5.2.16 on 2026-09-19 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0018_asignar_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomantenimiento',
            name='mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='mantenimiento.mantenimiento'),
        ),
    ]
