# Generated by Django 5.2.16 on 2026-09-19 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0030_hmac_propio_confirmado'),
        ('mantenimiento', '0019_proteger_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadplanificada',
            name='unidad_negocio',
            field=models.ForeignKey(blank=True, help_text='Cliente al que corresponde. Vacío = actividad interna, visible para todos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_planificadas', to='catalogo.unidadnegocio'),
        ),
    ]
