# Generated by Django 5.2.16 on 2026-09-26 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0020_actividad_unidad_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomantenimiento',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='firmamantenimiento',
            name='firmado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
