# Generated by Django 5.2.16 on 2026-09-26 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0022_firma_unica_por_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreEnConflicto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocurrido_en', models.DateTimeField(help_text='Cuándo cerró el técnico de verdad, en la farmacia (no cuándo llegó al servidor).')),
                ('payload_rechazado', models.JSONField(default=dict, help_text='El cierre tal como lo mandó el técnico: resultado, tiempo real, estado del equipo.')),
                ('estado_al_llegar', models.CharField(help_text='En qué estado estaba el mantenimiento cuando la acción llegó al servidor.', max_length=20)),
                ('motivo', models.TextField(help_text='Por qué se rechazó, en los términos del servicio que lo rechazó.')),
                ('revisado', models.BooleanField(default=False)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('resolucion', models.TextField(blank=True, help_text='Qué se decidió: se aplicó el cierre del técnico, o por qué se descartó.')),
                ('escalado_en', models.DateTimeField(blank=True, help_text='Cuándo se reenvió el aviso por seguir sin revisar (ver apps.mantenimiento.services.escalar_cierres_en_conflicto). Evita reescalar en cada corrida.', null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_en_conflicto', to='mantenimiento.mantenimiento')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_en_conflicto_revisados', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_en_conflicto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre en conflicto',
                'verbose_name_plural': 'Cierres en conflicto',
                'db_table': 'cierre_en_conflicto',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AccionOfflineAplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_id', models.PositiveIntegerField(help_text='id de la fila en la ColaOffline del teléfono (autoincremental por dispositivo).')),
                ('tipo', models.CharField(help_text='Acción aplicada, para poder leer la tabla.', max_length=40)),
                ('respuesta_json', models.JSONField(blank=True, default=dict, help_text='Cuerpo que se devolvió la primera vez; es lo que se repite en un reintento.')),
                ('estado_http', models.PositiveSmallIntegerField(default=200, help_text='Código que se devolvió la primera vez (200/201, o 409 si fue conflicto).')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_offline_aplicadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acción offline aplicada',
                'verbose_name_plural': 'Acciones offline aplicadas',
                'db_table': 'accion_offline_aplicada',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'origen_id'), name='accion_offline_unica_por_dispositivo')],
            },
        ),
    ]
