# Generated by Django 5.2.16 on 2026-07-17 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(help_text='Ej. despliegue.crear, despliegue.aprobar, farmacia.editar', max_length=100)),
                ('modelo', models.CharField(blank=True, help_text='Etiqueta del modelo afectado', max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('objeto_repr', models.CharField(blank=True, help_text='str() del objeto al momento del evento', max_length=255)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'db_table': 'evento_auditoria',
                'ordering': ['-timestamp'],
            },
        ),
    ]
