# Generated by Django 5.2.16 on 2026-08-02 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('catalogo', '0009_alter_farmacia_unidad_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoauditoria',
            name='unidad_negocio',
            field=models.ForeignKey(blank=True, help_text='Tenant del objeto auditado, derivado automáticamente en registrar_evento(). Vacío = evento de un recurso compartido (ej. OrdenCompra) o sin tenant único (ej. actividad de cumplimiento dirigida a varias unidades) — visible para todos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to='catalogo.unidadnegocio'),
        ),
    ]
