# Generated by Django 5.2.16 on 2026-09-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_eventoauditoria_unidad_negocio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventoauditoria',
            options={'ordering': ['-timestamp', '-pk'], 'verbose_name': 'Evento de auditoría', 'verbose_name_plural': 'Eventos de auditoría'},
        ),
    ]
